// The rst external scanner, ported from https://github.com/stsewd/tree-sitter-rst (src/scanner.c, MIT
// license) to ned's scanner interface. The algorithm and its state are the
// upstream grammar's; only the vocabulary is ned's.

#include "Editor/Parse/Scanner.h"
#include "Editor/Parse/ScannerSupport.h"

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace ned::editor::languages::scanners::rst {

using namespace ned::editor::parse::scanner;

// --- scanner.c (from the same grammar) ---
// --- scanner.h (from the same grammar) ---
#ifndef TREE_SITTER_RST_SCANNER_H
#define TREE_SITTER_RST_SCANNER_H

#define RST_SCANNER_STACK_MAX_CAPACITY 99

typedef struct RSTScanner RSTScanner;

/// Wrapper struct around ``Lexer`` to track indentation levels.
///
/// TODO: track consumed_chars?
struct RSTScanner {
  // Wrappers around the lexer.
  Lexer* lexer;
  const bool* valid_symbols;

  int32_t lookahead;
  int32_t previous;

  void (*advance)(RSTScanner* scanner);
  void (*skip)(RSTScanner* scanner);

  // Functions for the indentation levels.
  int* indent_stack;
  unsigned length;

  void (*push)(RSTScanner* scanner, int value);
  int (*pop)(RSTScanner* scanner);
  int (*back)(const RSTScanner* scanner);

  // Functions for the scanner.
  unsigned (*serialize)(RSTScanner* scanner, char* buffer);
  void (*deserialize)(RSTScanner* scanner, const char* buffer, unsigned length);
  bool (*scan)(RSTScanner* scanner);
};

static RSTScanner* new_rst_scanner();
static void destroy_rst_scanner(RSTScanner* scanner);

static void rst_scanner_advance(RSTScanner* scanner);
static void rst_scanner_skip(RSTScanner* scanner);

static void rst_scanner_push(RSTScanner* scanner, int value);
static int rst_scanner_pop(RSTScanner* scanner);
static int rst_scanner_back(const RSTScanner* scanner);

static unsigned rst_scanner_serialize(RSTScanner* scanner, char* buffer);
static void rst_scanner_deserialize(RSTScanner* scanner, const char* buffer, unsigned length);
static bool rst_scanner_scan(RSTScanner* scanner);

#endif /* ifndef TREE_SITTER_RST_SCANNER_H */

// --- chars.c (from the same grammar) ---
// --- chars.h (from the same grammar) ---
#ifndef TREE_SITTER_RST_CHARS_H_
#define TREE_SITTER_RST_CHARS_H_

// --- scanner.h already inlined above ---

#define CHAR_EOF 0
#define CHAR_NEWLINE 10
#define CHAR_CARRIAGE_RETURN 13
#define CHAR_NBSP 160

#define CHAR_SPACE ' '
#define CHAR_FORM_FEED '\f'
#define CHAR_TAB '\t'
#define CHAR_VERTICAL_TAB '\v'

// number of spaces to expand a tab to
#define TAB_STOP 8

static bool is_newline(int32_t c);
static bool is_space(int32_t c);
static bool is_number(int32_t c);
static bool is_abc_lower(int32_t c);
static bool is_abc_upper(int32_t c);
static bool is_abc(int32_t c);
static bool is_alphanumeric(int32_t c);

static bool is_adornment_char(int32_t c);

static bool is_start_char(int32_t c);
static bool is_end_char(int32_t c);
static bool is_inline_markup_start_char(int32_t c);
static bool is_inline_markup_end_char(int32_t c);

static bool is_internal_reference_char(int32_t c);

static bool is_char_bullet(int32_t c);
static bool is_numeric_bullet(int32_t c);
static bool is_numeric_bullet_simple(int32_t c);
static bool is_numeric_bullet_roman_lower(int32_t c);
static bool is_numeric_bullet_roman_upper(int32_t c);
static bool is_numeric_bullet_abc_lower(int32_t c);
static bool is_numeric_bullet_abc_upper(int32_t c);
static bool is_known_schema(char* string, unsigned string_len);
static bool is_invalid_uri_char(int32_t c);

#define CHAR_EMDASH 8212

static bool is_attribution_mark(int32_t c);

static int get_indent_level(RSTScanner* scanner);

#endif /* ifndef TREE_SITTER_RST_CHARS_H_ */

// --- punctuation_chars.h (from the same grammar) ---
// This file is generated by utils/gen_punctuation_chars.py, DO NOT EDIT.

#ifndef TREE_SITTER_RST_PUNCTUATION_CHARS_H_
#define TREE_SITTER_RST_PUNCTUATION_CHARS_H_

const int32_t start_chars[] = {
  '"',
  '\'',
  '(',
  '<',
  '\\',
  '[',
  '{',
  0xf3a,
  0xf3c,
  0x169b,
  0x2045,
  0x207d,
  0x208d,
  0x2329,
  0x2768,
  0x276a,
  0x276c,
  0x276e,
  0x2770,
  0x2772,
  0x2774,
  0x27c5,
  0x27e6,
  0x27e8,
  0x27ea,
  0x27ec,
  0x27ee,
  0x2983,
  0x2985,
  0x2987,
  0x2989,
  0x298b,
  0x298d,
  0x298f,
  0x2991,
  0x2993,
  0x2995,
  0x2997,
  0x29d8,
  0x29da,
  0x29fc,
  0x2e22,
  0x2e24,
  0x2e26,
  0x2e28,
  0x3008,
  0x300a,
  0x300c,
  0x300e,
  0x3010,
  0x3014,
  0x3016,
  0x3018,
  0x301a,
  0x301d,
  0x301d,
  0xfd3e,
  0xfe17,
  0xfe35,
  0xfe37,
  0xfe39,
  0xfe3b,
  0xfe3d,
  0xfe3f,
  0xfe41,
  0xfe43,
  0xfe47,
  0xfe59,
  0xfe5b,
  0xfe5d,
  0xff08,
  0xff3b,
  0xff5b,
  0xff5f,
  0xff62,
  0xab,
  0x2018,
  0x201c,
  0x2039,
  0x2e02,
  0x2e04,
  0x2e09,
  0x2e0c,
  0x2e1c,
  0x2e20,
  0x201a,
  0x201e,
  0xbb,
  0x2019,
  0x201d,
  0x203a,
  0x2e03,
  0x2e05,
  0x2e0a,
  0x2e0d,
  0x2e1d,
  0x2e21,
  0x201b,
  0x201f,
};

const int32_t delim_chars[] = {
  '\\',
  '-',
  '/',
  ':',
  0x58a,
  0xa1,
  0xb7,
  0xbf,
  0x37e,
  0x387,
  0x55f,
  0x589,
  0x5be,
  0x5c0,
  0x5c3,
  0x5c6,
  0x5f3,
  0x5f4,
  0x609,
  0x60a,
  0x60c,
  0x60d,
  0x61b,
  0x61e,
  0x61f,
  0x66d,
  0x6d4,
  0x70d,
  0x7f9,
  0x83e,
  0x964,
  0x965,
  0x970,
  0xdf4,
  0xe4f,
  0xe5a,
  0xe5b,
  0xf12,
  0xf85,
  0xfd4,
  0x104f,
  0x10fb,
  0x1368,
  0x1400,
  0x166d,
  0x166e,
  0x16ed,
  0x1735,
  0x1736,
  0x17d6,
  0x17da,
  0x180a,
  0x1944,
  0x1945,
  0x19de,
  0x19df,
  0x1a1e,
  0x1a1f,
  0x1aa6,
  0x1aad,
  0x1b60,
  0x1c3f,
  0x1c7e,
  0x1c7f,
  0x1cd3,
  0x2017,
  0x2027,
  0x2038,
  0x203e,
  0x2043,
  0x2051,
  0x2053,
  0x205e,
  0x2cfc,
  0x2cfe,
  0x2cff,
  0x2e00,
  0x2e01,
  0x2e08,
  0x2e0b,
  0x2e1b,
  0x2e1e,
  0x2e1f,
  0x2e2e,
  0x2e30,
  0x2e31,
  0x3003,
  0x301c,
  0x3030,
  0x303d,
  0x30a0,
  0x30fb,
  0xa4fe,
  0xa4ff,
  0xa60f,
  0xa673,
  0xa67e,
  0xa6f7,
  0xa877,
  0xa8ce,
  0xa8cf,
  0xa8fa,
  0xa92e,
  0xa92f,
  0xa95f,
  0xa9cd,
  0xa9de,
  0xa9df,
  0xaa5f,
  0xaade,
  0xaadf,
  0xabeb,
  0xfe16,
  0xfe19,
  0xfe32,
  0xfe45,
  0xfe46,
  0xfe4c,
  0xfe52,
  0xfe58,
  0xfe61,
  0xfe63,
  0xfe68,
  0xfe6a,
  0xfe6b,
  0xff03,
  0xff07,
  0xff0a,
  0xff0f,
  0xff1a,
  0xff1b,
  0xff1f,
  0xff20,
  0xff3c,
  0xff61,
  0xff64,
  0xff65,
  0x10100,
  0x10101,
  0x1039f,
  0x103d0,
  0x10857,
  0x1091f,
  0x1093f,
  0x10a58,
  0x10a7f,
  0x10b3f,
  0x110bb,
  0x110bc,
  0x110c1,
  0x12473,
};
const int32_t delim_chars_range[][2] = {
  { 0x55a, 0x55f },
  { 0x66a, 0x66d },
  { 0x700, 0x70d },
  { 0x7f7, 0x7f9 },
  { 0x830, 0x83e },
  { 0xf04, 0xf12 },
  { 0xfd0, 0xfd4 },
  { 0x104a, 0x104f },
  { 0x1361, 0x1368 },
  { 0x16eb, 0x16ed },
  { 0x17d4, 0x17d6 },
  { 0x17d8, 0x17da },
  { 0x1800, 0x180a },
  { 0x1aa0, 0x1aa6 },
  { 0x1aa8, 0x1aad },
  { 0x1b5a, 0x1b60 },
  { 0x1c3b, 0x1c3f },
  { 0x2010, 0x2017 },
  { 0x2020, 0x2027 },
  { 0x2030, 0x2038 },
  { 0x203b, 0x203e },
  { 0x2041, 0x2043 },
  { 0x2047, 0x2051 },
  { 0x2055, 0x205e },
  { 0x2cf9, 0x2cfc },
  { 0x2e06, 0x2e08 },
  { 0x2e0e, 0x2e1b },
  { 0x2e2a, 0x2e2e },
  { 0x3001, 0x3003 },
  { 0xa60d, 0xa60f },
  { 0xa6f2, 0xa6f7 },
  { 0xa874, 0xa877 },
  { 0xa8f8, 0xa8fa },
  { 0xa9c1, 0xa9cd },
  { 0xaa5c, 0xaa5f },
  { 0xfe10, 0xfe16 },
  { 0xfe30, 0xfe32 },
  { 0xfe49, 0xfe4c },
  { 0xfe50, 0xfe52 },
  { 0xfe54, 0xfe58 },
  { 0xfe5f, 0xfe61 },
  { 0xff01, 0xff03 },
  { 0xff05, 0xff07 },
  { 0xff0c, 0xff0f },
  { 0x10a50, 0x10a58 },
  { 0x10b39, 0x10b3f },
  { 0x110be, 0x110c1 },
  { 0x12470, 0x12473 },
};

const int32_t end_chars[] = {
  '\\',
  '\\',
  '.',
  ',',
  ';',
  '!',
  '?',
  '"',
  '\'',
  ')',
  '>',
  '\\',
  ']',
  '}',
  0xf3b,
  0xf3d,
  0x169c,
  0x2046,
  0x207e,
  0x208e,
  0x232a,
  0x2769,
  0x276b,
  0x276d,
  0x276f,
  0x2771,
  0x2773,
  0x2775,
  0x27c6,
  0x27e7,
  0x27e9,
  0x27eb,
  0x27ed,
  0x27ef,
  0x2984,
  0x2986,
  0x2988,
  0x298a,
  0x298c,
  0x298e,
  0x2990,
  0x2992,
  0x2994,
  0x2996,
  0x2998,
  0x29d9,
  0x29db,
  0x29fd,
  0x2e23,
  0x2e25,
  0x2e27,
  0x2e29,
  0x3009,
  0x300b,
  0x300d,
  0x300f,
  0x3011,
  0x3015,
  0x3017,
  0x3019,
  0x301b,
  0x301e,
  0x301f,
  0xfd3f,
  0xfe18,
  0xfe36,
  0xfe38,
  0xfe3a,
  0xfe3c,
  0xfe3e,
  0xfe40,
  0xfe42,
  0xfe44,
  0xfe48,
  0xfe5a,
  0xfe5c,
  0xfe5e,
  0xff09,
  0xff3d,
  0xff5d,
  0xff60,
  0xff63,
  0xbb,
  0x2019,
  0x201d,
  0x203a,
  0x2e03,
  0x2e05,
  0x2e0a,
  0x2e0d,
  0x2e1d,
  0x2e21,
  0x201b,
  0x201f,
  0xab,
  0x2018,
  0x201c,
  0x2039,
  0x2e02,
  0x2e04,
  0x2e09,
  0x2e0c,
  0x2e1c,
  0x2e20,
  0x201a,
  0x201e,
};

#endif /* ifndef TREE_SITTER_RST_PUNCTUATION_CHARS_H_ */

static bool is_newline(int32_t c)
{
  const int32_t newline_chars[] = {
    CHAR_EOF,
    CHAR_NEWLINE,
    CHAR_CARRIAGE_RETURN,
  };
  const int length = sizeof(newline_chars) / sizeof(int32_t);
  for (int i = 0; i < length; i++) {
    if (c == newline_chars[i]) {
      return true;
    }
  }
  return false;
}

static bool is_space(int32_t c)
{
  const int32_t space_chars[] = {
    CHAR_SPACE,
    CHAR_FORM_FEED,
    CHAR_TAB,
    CHAR_VERTICAL_TAB,
    CHAR_NBSP,
  };
  const int length = sizeof(space_chars) / sizeof(int32_t);
  bool is_space_char = false;
  for (int i = 0; i < length; i++) {
    if (c == space_chars[i]) {
      is_space_char = true;
      break;
    }
  }
  return is_space_char || is_newline(c);
}

static bool is_number(int32_t c)
{
  const int32_t upper = 48;
  const int32_t lower = 57;
  return c >= upper && c <= lower;
}

static bool is_abc_lower(int32_t c)
{
  const int32_t upper = 97;
  const int32_t lower = 122;
  return c >= upper && c <= lower;
}

static bool is_abc_upper(int32_t c)
{
  const int32_t upper = 65;
  const int32_t lower = 90;
  return c >= upper && c <= lower;
}

static bool is_abc(int32_t c)
{
  return is_abc_lower(c) || is_abc_upper(c);
}

static bool is_alphanumeric(int32_t c)
{
  return is_abc(c) || is_number(c);
}

/// Check if it's an adornment char.
///
/// Adorment characters are used for sections and transitions.
static bool is_adornment_char(int32_t c)
{
  const int32_t adornment_chars[] = {
    '!',
    '"',
    '#',
    '$',
    '%',
    '&',
    '\'',
    '(',
    ')',
    '*',
    '+',
    ',',
    '-',
    '.',
    '/',
    ':',
    ';',
    '<',
    '=',
    '>',
    '?',
    '@',
    '[',
    '\\',
    ']',
    '^',
    '_',
    '`',
    '{',
    '|',
    '}',
    '~',
  };
  const int length = sizeof(adornment_chars) / sizeof(int32_t);
  for (int i = 0; i < length; i++) {
    if (c == adornment_chars[i]) {
      return true;
    }
  }
  return false;
}

static bool is_delim_char(int32_t c)
{
  int length = sizeof(delim_chars) / sizeof(int32_t);
  for (int i = 0; i < length; i++) {
    if (c == delim_chars[i]) {
      return true;
    }
  }
  length = sizeof(delim_chars_range) / sizeof(delim_chars_range[0]);
  for (int i = 0; i < length; i++) {
    if (c >= delim_chars_range[i][0] && c <= delim_chars_range[i][1]) {
      return true;
    }
  }
  return false;
}

/// Check if it's a start char.
///
/// Some tokens can start after non-whitespace chars.
static bool is_start_char(int32_t c)
{
  int length = sizeof(start_chars) / sizeof(int32_t);
  for (int i = 0; i < length; i++) {
    if (c == start_chars[i]) {
      return true;
    }
  }
  return is_delim_char(c);
}

/// Check if it's an end char.
///
/// Some tokens can end after non-whitespace chars.
static bool is_end_char(int32_t c)
{
  int length = sizeof(end_chars) / sizeof(int32_t);
  for (int i = 0; i < length; i++) {
    if (c == end_chars[i]) {
      return true;
    }
  }
  return is_delim_char(c);
}

static bool is_inline_markup_start_char(int32_t c)
{
  const int32_t inline_markup_chars[] = {
    '*', // *emphasis*, and **strong**.
    '`', // `interpreted text`, ``literals``, `hyperlink references`_, and `anonymous references`__.
    '|', // |substitution references|.
    '_', // _`inline internal target`.
    '[', // [foot-note]_.
  };
  const int length = sizeof(inline_markup_chars) / sizeof(int32_t);
  for (int i = 0; i < length; i++) {
    if (c == inline_markup_chars[i]) {
      return true;
    }
  }
  return false;
}

static bool is_inline_markup_end_char(int32_t c)
{
  const int32_t inline_markup_chars[] = {
    '*', // *emphasis*, and **strong**.
    '`', // `interpreted text`, ``literals``, _`inline internal target`,
    // `hyperlink references`_, and `anonymous references`__.
    '|', // |substitution references|.
    ']', // [foot-note]_.
  };
  const int length = sizeof(inline_markup_chars) / sizeof(int32_t);
  for (int i = 0; i < length; i++) {
    if (c == inline_markup_chars[i]) {
      return true;
    }
  }
  return false;
}

/// Check if it's an internal reference char.
///
/// References and some other names can't have two consecutive internal characters.
static bool is_internal_reference_char(int32_t c)
{
  const int32_t internal_chars[] = { '-', '_', '.', ':', '+' };
  const int length = sizeof(internal_chars) / sizeof(int32_t);
  for (int i = 0; i < length; i++) {
    if (c == internal_chars[i]) {
      return true;
    }
  }
  return false;
}

/// Check if it's a bullet char.
///
/// Lists use these characters to start an item.
static bool is_char_bullet(int32_t c)
{
  const int32_t bullets[] = {
    '*',
    '+',
    '-',
    8226, // '•'
    8227, // '‣'
    8259, // '⁃'
  };
  const int length = sizeof(bullets) / sizeof(int32_t);
  for (int i = 0; i < length; i++) {
    if (c == bullets[i]) {
      return true;
    }
  }
  return false;
}

/// Check if it's a numeric bullet char.
///
/// Lists cacn use different number formats to start an item.
static bool is_numeric_bullet(int32_t c)
{
  return (
      is_numeric_bullet_simple(c)
      || is_numeric_bullet_roman_lower(c)
      || is_numeric_bullet_roman_upper(c)
      || is_numeric_bullet_abc_lower(c)
      || is_numeric_bullet_abc_upper(c));
}

static bool is_numeric_bullet_simple(int32_t c)
{
  return is_number(c) || c == '#';
}

static bool is_numeric_bullet_roman_lower(int32_t c)
{
  const int32_t valid_chars[] = {
    'i',
    'v',
    'x',
    'l',
    'c',
    'd',
    'm',
  };
  const int length = sizeof(valid_chars) / sizeof(int32_t);
  for (int i = 0; i < length; i++) {
    if (c == valid_chars[i]) {
      return true;
    }
  }
  return false;
}

static bool is_numeric_bullet_roman_upper(int32_t c)
{
  const int32_t valid_chars[] = {
    'I',
    'V',
    'X',
    'L',
    'C',
    'D',
    'M',
  };
  const int length = sizeof(valid_chars) / sizeof(int32_t);
  for (int i = 0; i < length; i++) {
    if (c == valid_chars[i]) {
      return true;
    }
  }
  return false;
}

static bool is_numeric_bullet_abc_lower(int32_t c)
{
  return is_abc_lower(c);
}

static bool is_numeric_bullet_abc_upper(int32_t c)
{
  return is_abc_upper(c);
}

/// Check if it's a valid attribution char.
///
/// Attribution chars are used to denot the author of a quote.
static bool is_attribution_mark(int32_t c)
{
  const int32_t valid_chars[] = {
    '-',
    CHAR_EMDASH,
  };
  const int length = sizeof(valid_chars) / sizeof(int32_t);
  for (int i = 0; i < length; i++) {
    if (c == valid_chars[i]) {
      return true;
    }
  }
  return false;
}

/// Get the current indentation level.
///
/// The scanner should be set to a char after a newline.
static int get_indent_level(RSTScanner* scanner)
{
  int32_t current = scanner->lookahead;
  int indent = 0;

  while (true) {
    current = scanner->lookahead;
    if (current == CHAR_SPACE || current == CHAR_VERTICAL_TAB || current == CHAR_FORM_FEED) {
      indent += 1;
    } else if (current == CHAR_TAB) {
      indent += TAB_STOP;
    } else {
      break;
    }
    scanner->advance(scanner);
  }

  return indent;
}

static bool is_known_schema(char* string, unsigned string_len)
{
  const char* valid_schemas[] = {
    "http",
    "https",
    "ftp",
    "mailto",
    "telnet",
    "ssh",
  };
  const int length = sizeof(valid_schemas) / sizeof(char*);
  for (int i = 0; i < length; i++) {
    if (string_len != strlen(valid_schemas[i])) {
      continue;
    }
    int result = memcmp(string, valid_schemas[i], string_len);
    if (result == 0) {
      return true;
    }
  }
  return false;
}

static bool is_invalid_uri_char(int32_t c)
{
  const int32_t invalid_chars[] = {
    '^',
    '}',
    '{',
    '\\',
  };
  const int length = sizeof(invalid_chars) / sizeof(int32_t);
  for (int i = 0; i < length; i++) {
    if (c == invalid_chars[i]) {
      return true;
    }
  }
  return false;
}

// --- parser.c (from the same grammar) ---
// --- parser.h (from the same grammar) ---
#ifndef TREE_SITTER_RST_PARSER_H_
#define TREE_SITTER_RST_PARSER_H_

// --- scanner.h already inlined above ---
// --- tokens.h (from the same grammar) ---
#ifndef TREE_SITTER_RST_TOKENS_H_
#define TREE_SITTER_RST_TOKENS_H_

enum TokenType {
  // Whitespace
  T_NEWLINE,
  T_BLANKLINE,
  T_INDENT,
  T_NEWLINE_INDENT,
  T_DEDENT,

  // Sections
  T_OVERLINE,
  T_UNDERLINE,

  // Transitions
  T_TRANSITION,

  // Lists
  T_CHAR_BULLET,
  T_NUMERIC_BULLET,
  T_FIELD_MARK,
  T_FIELD_MARK_END,

  // Literal blocks
  T_LITERAL_INDENTED_BLOCK_MARK,
  T_LITERAL_QUOTED_BLOCK_MARK,
  T_QUOTED_LITERAL_BLOCK,

  // Line blocks
  T_LINE_BLOCK_MARK,

  // Block quotes
  T_ATTRIBUTION_MARK,

  // Doctest blocks
  T_DOCTEST_BLOCK_MARK,

  // Inline markup
  T_TEXT,
  T_EMPHASIS,
  T_STRONG,
  T_INTERPRETED_TEXT,
  T_INTERPRETED_TEXT_PREFIX,
  T_ROLE_NAME_PREFIX,
  T_ROLE_NAME_SUFFIX,
  T_LITERAL,
  T_SUBSTITUTION_REFERENCE,
  T_INLINE_TARGET,
  T_FOOTNOTE_REFERENCE,
  T_CITATION_REFERENCE,
  T_REFERENCE,
  T_STANDALONE_HYPERLINK,

  // Markup blocks
  T_EXPLICIT_MARKUP_START,
  T_FOOTNOTE_LABEL,
  T_CITATION_LABEL,
  T_TARGET_NAME,
  T_ANONYMOUS_TARGET_MARK,
  T_DIRECTIVE_NAME,
  T_SUBSTITUTION_MARK,
  T_EMPTY_COMMENT,

  T_INVALID_TOKEN,
};

#endif /* TREE_SITTER_RST_TOKENS_H_ */

#define IM_EMPHASIS 1u << 0u
#define IM_STRONG 1u << 1u
#define IM_INTERPRETED_TEXT 1u << 2u
#define IM_INTERPRETED_TEXT_PREFIX 1u << 3u
#define IM_LITERAL 1u << 4u
#define IM_SUBSTITUTION_REFERENCE 1u << 5u
#define IM_INLINE_TARGET 1u << 6u
#define IM_FOOTNOTE_REFERENCE 1u << 7u
#define IM_CITATION_REFERENCE 1u << 8u
#define IM_REFERENCE 1u << 9u

static bool parse_indent(RSTScanner* scanner);
static bool parse_overline(RSTScanner* scanner);
static bool parse_underline(RSTScanner* scanner);
static bool fallback_adornment(RSTScanner* scanner, int32_t adornment, int adornment_length);

static bool parse_char_bullet(RSTScanner* scanner);
static bool parse_numeric_bullet(RSTScanner* scanner);
static bool parse_inner_numeric_bullet(RSTScanner* scanner, bool parenthesized);
static bool parse_explict_markup_start(RSTScanner* scanner);
static bool parse_inner_list_element(RSTScanner* scanner, int consumed_chars, enum TokenType token_type);
static bool parse_field_mark(RSTScanner* scanner);
static bool parse_field_mark_end(RSTScanner* scanner);
static bool parse_inner_field_mark(RSTScanner* scanner);

static bool parse_literal_block_mark(RSTScanner* scanner);
static bool parse_innner_literal_block_mark(RSTScanner* scanner);
static bool parse_quoted_literal_block(RSTScanner* scanner);

static bool parse_line_block_mark(RSTScanner* scanner);

static bool parse_attribution_mark(RSTScanner* scanner);

static bool parse_doctest_block_mark(RSTScanner* scanner);

static bool parse_label(RSTScanner* scanner);
static int parse_inner_label_name(RSTScanner* scanner);
static bool parse_inner_alphanumeric_label(RSTScanner* scanner);
static bool parse_target_name(RSTScanner* scanner);
static bool parse_anonymous_target_mark(RSTScanner* scanner);
static bool parse_directive_mark(RSTScanner* scanner);
static bool parse_substitution_mark(RSTScanner* scanner);

static bool parse_inline_markup(RSTScanner* scanner);
static bool parse_inner_inline_markup(RSTScanner* scanner, unsigned type);
static bool parse_reference(RSTScanner* scanner);
static bool parse_inner_reference(RSTScanner* scanner);
static bool parse_standalone_hyperlink(RSTScanner* scanner);
static bool parse_inner_standalone_hyperlink(RSTScanner* scanner);
static bool parse_role(RSTScanner* scanner);
static bool parse_role_name(RSTScanner* scanner);
static bool parse_inner_role(RSTScanner* scanner);
static bool parse_text(RSTScanner* scanner, bool mark_end);

#endif /* TREE_SITTER_RST_PARSER_H_ */

// --- chars.h already inlined above ---
// --- tokens.h already inlined above ---

static bool parse_indent(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  lexer->markEnd(lexer);

  int indent = 0;
  int newlines = 0;
  while (true) {
    if (scanner->lookahead == CHAR_SPACE
        || scanner->lookahead == CHAR_VERTICAL_TAB
        || scanner->lookahead == CHAR_FORM_FEED
        || scanner->lookahead == CHAR_NBSP) {
      indent += 1;
    } else if (scanner->lookahead == CHAR_TAB) {
      indent += TAB_STOP;
    } else if (scanner->lookahead == CHAR_EOF) {
      indent = 0;
      newlines++;
      break;
    } else if (scanner->lookahead == CHAR_CARRIAGE_RETURN) {
      indent = 0;
    } else if (scanner->lookahead == CHAR_NEWLINE) {
      newlines++;
      indent = 0;
    } else {
      break;
    }
    scanner->skip(scanner);
  }

  int current_indent = scanner->back(scanner);
  if (indent > current_indent && valid_symbols[T_INDENT]) {
    scanner->push(scanner, indent);
    lexer->resultSymbol = T_INDENT;
    return true;
  }
  if (newlines) {
    if (indent < current_indent && valid_symbols[T_DEDENT]) {
      scanner->pop(scanner);
      lexer->resultSymbol = T_DEDENT;
      return true;
    }

    if ((newlines > 1 || scanner->lookahead == CHAR_EOF) && valid_symbols[T_BLANKLINE]) {
      lexer->resultSymbol = T_BLANKLINE;
      return true;
    }

    if (newlines == 1 && valid_symbols[T_NEWLINE_INDENT] && indent > current_indent) {
      scanner->push(scanner, indent);
      lexer->resultSymbol = T_NEWLINE_INDENT;
      return true;
    }

    if (valid_symbols[T_NEWLINE]) {
      lexer->resultSymbol = T_NEWLINE;
      return true;
    }
  }
  return false;
}

static bool parse_overline(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;
  int32_t adornment = scanner->lookahead;

  if (!is_adornment_char(scanner->lookahead)
      || (!valid_symbols[T_OVERLINE] && !valid_symbols[T_TRANSITION])) {
    return false;
  }

  scanner->advance(scanner);
  lexer->markEnd(lexer);
  int overline_length = 1;

  while (true) {
    if (scanner->lookahead != adornment) {
      bool ok = fallback_adornment(scanner, adornment, overline_length);
      if (ok) {
        return true;
      }
      if (is_space(scanner->lookahead)) {
        break;
      }
      return parse_text(scanner, false);
    }
    scanner->advance(scanner);
    overline_length++;
  }

  // Mark the transition token
  lexer->markEnd(lexer);

  // Consume all whitespaces.
  while (is_space(scanner->lookahead) && !is_newline(scanner->lookahead)) {
    scanner->advance(scanner);
  }

  if (!is_newline(scanner->lookahead)) {
    return parse_text(scanner, false);
  }

  scanner->advance(scanner);

  bool is_empty = true;
  while (!is_newline(scanner->lookahead)) {
    if (!is_space(scanner->lookahead)) {
      is_empty = false;
    }
    scanner->advance(scanner);
  }

  if (is_empty) {
    // Transitions need to be at least 4 chars long
    if (overline_length >= 4 && valid_symbols[T_TRANSITION]) {
      lexer->resultSymbol = T_TRANSITION;
      return true;
    }
    return parse_text(scanner, false);
  }

  scanner->advance(scanner);

  int underline_length = 0;

  while (!is_newline(scanner->lookahead)) {
    if (scanner->lookahead != adornment) {
      if (is_space(scanner->lookahead)) {
        break;
      }
      return parse_text(scanner, false);
    }
    scanner->advance(scanner);
    underline_length++;
  }

  // Consume all whitespaces.
  while (is_space(scanner->lookahead) && !is_newline(scanner->lookahead)) {
    scanner->advance(scanner);
  }

  if (!is_newline(scanner->lookahead)) {
    return parse_text(scanner, false);
  }

  // The overline_length and the underline_length length must match
  if (overline_length >= 1 && overline_length == underline_length) {
    lexer->resultSymbol = T_OVERLINE;
    return true;
  }

  return parse_text(scanner, false);
}

static bool parse_underline(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;
  int32_t adornment = scanner->lookahead;

  if (!is_adornment_char(scanner->lookahead)
      || (!valid_symbols[T_UNDERLINE] && !valid_symbols[T_TRANSITION])) {
    return false;
  }

  scanner->advance(scanner);
  lexer->markEnd(lexer);
  int underline_length = 1;

  while (!is_newline(scanner->lookahead)) {
    if (scanner->lookahead != adornment) {
      bool ok = fallback_adornment(scanner, adornment, underline_length);
      if (ok) {
        return true;
      }
      if (is_space(scanner->lookahead)) {
        break;
      }
      return parse_text(scanner, false);
    }
    scanner->advance(scanner);
    underline_length++;
  }

  // Mark the transition token
  lexer->markEnd(lexer);

  // Consume all whitespaces.
  while (is_space(scanner->lookahead) && !is_newline(scanner->lookahead)) {
    scanner->advance(scanner);
  }

  if (!is_newline(scanner->lookahead)) {
    return parse_text(scanner, false);
  }

  // Transitions need to be at least 4 chars long
  if (underline_length >= 4 && valid_symbols[T_TRANSITION]) {
    lexer->resultSymbol = T_TRANSITION;
    return true;
  }

  if (underline_length >= 1 && valid_symbols[T_UNDERLINE]) {
    lexer->resultSymbol = T_UNDERLINE;
    return true;
  }

  return parse_text(scanner, false);
}

/// If the adnorment is not valid, try to parse a different token.
///
/// Lots of adornments are also valid tokens, so we need to check for each one of them.
static bool fallback_adornment(RSTScanner* scanner, int32_t adornment, int adornment_length)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  if (adornment_length == 1) {
    if (is_space(scanner->lookahead)) {
      if (is_char_bullet(adornment) && valid_symbols[T_CHAR_BULLET]) {
        bool ok = parse_inner_list_element(scanner, 1, T_CHAR_BULLET);
        if (ok) {
          return true;
        }
      } else if (adornment == '|' && valid_symbols[T_LINE_BLOCK_MARK]) {
        bool ok = parse_inner_list_element(scanner, 1, T_LINE_BLOCK_MARK);
        if (ok) {
          return true;
        }
      }
    } else {
      if (adornment == '*' && valid_symbols[T_EMPHASIS]) {
        return parse_inner_inline_markup(scanner, IM_EMPHASIS);
      }
      if (adornment == ':' && (valid_symbols[T_ROLE_NAME_PREFIX] || valid_symbols[T_ROLE_NAME_SUFFIX])) {
        bool ok = parse_inner_role(scanner);
        if (ok) {
          return true;
        }
        return parse_text(scanner, false);
      }
      if (adornment == ':' && valid_symbols[T_FIELD_MARK]) {
        bool ok = parse_inner_field_mark(scanner);
        if (ok) {
          return true;
        }
        return parse_text(scanner, false);
      }
      if (adornment == '`' && (valid_symbols[T_INTERPRETED_TEXT] || valid_symbols[T_INTERPRETED_TEXT_PREFIX] || valid_symbols[T_REFERENCE])) {
        return parse_inner_inline_markup(scanner, IM_INTERPRETED_TEXT | IM_INTERPRETED_TEXT_PREFIX | IM_REFERENCE);
      }
      if (adornment == '|' && valid_symbols[T_SUBSTITUTION_REFERENCE]) {
        return parse_inner_inline_markup(scanner, IM_SUBSTITUTION_REFERENCE);
      }
      if (adornment == '_' && scanner->lookahead == '`' && valid_symbols[T_INLINE_TARGET]) {
        return parse_inner_inline_markup(scanner, IM_INLINE_TARGET);
      }
      if (adornment == '[' && (valid_symbols[T_FOOTNOTE_REFERENCE] || valid_symbols[T_CITATION_REFERENCE])) {
        return parse_inner_inline_markup(scanner, IM_FOOTNOTE_REFERENCE | IM_CITATION_REFERENCE);
      }
      if (adornment == '#'
          && (scanner->lookahead == '.' || scanner->lookahead == ')')) {
        scanner->advance(scanner);
        bool ok = parse_inner_list_element(scanner, 2, T_NUMERIC_BULLET);
        if (ok) {
          return true;
        }
      }
      if (adornment == '(' && is_numeric_bullet(scanner->lookahead) && valid_symbols[T_NUMERIC_BULLET]) {
        return parse_inner_numeric_bullet(scanner, true);
      }
    }
  } else if (adornment_length >= 2) {
    if (is_space(scanner->lookahead)) {
      if (adornment_length == 3
          && adornment == '>'
          && valid_symbols[T_DOCTEST_BLOCK_MARK]) {
        lexer->markEnd(lexer);
        lexer->resultSymbol = T_DOCTEST_BLOCK_MARK;
        return true;
      }
      if (adornment_length == 2 && adornment == '.') {
        return parse_inner_list_element(scanner, 2, T_EXPLICIT_MARKUP_START);
      }
      if (adornment_length == 2
          && adornment == '_'
          && valid_symbols[T_ANONYMOUS_TARGET_MARK]) {
        lexer->markEnd(lexer);
        lexer->resultSymbol = T_ANONYMOUS_TARGET_MARK;
        return true;
      }
      if (adornment_length == 2
          && adornment == ':'
          && (valid_symbols[T_LITERAL_INDENTED_BLOCK_MARK] || valid_symbols[T_LITERAL_QUOTED_BLOCK_MARK])) {
        return parse_innner_literal_block_mark(scanner);
      }
    } else {
      if (adornment == '*' && valid_symbols[T_STRONG]) {
        return parse_inner_inline_markup(scanner, IM_STRONG);
      }
      if (adornment == '`' && valid_symbols[T_LITERAL]) {
        return parse_inner_inline_markup(scanner, IM_LITERAL);
      }
      if (adornment == '|' && valid_symbols[T_SUBSTITUTION_REFERENCE]) {
        return parse_inner_inline_markup(scanner, IM_SUBSTITUTION_REFERENCE);
      }
      if (adornment == '[' && (valid_symbols[T_FOOTNOTE_REFERENCE] || valid_symbols[T_CITATION_REFERENCE])) {
        return parse_inner_inline_markup(scanner, IM_FOOTNOTE_REFERENCE | IM_CITATION_REFERENCE);
      }
    }
  }
  return false;
}

bool parse_char_bullet(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;

  if (!is_char_bullet(scanner->lookahead) || !valid_symbols[T_CHAR_BULLET]) {
    return false;
  }

  scanner->advance(scanner);
  bool ok = parse_inner_list_element(scanner, 1, T_CHAR_BULLET);
  if (ok) {
    return true;
  }

  return parse_text(scanner, true);
}

static bool parse_numeric_bullet(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;

  if (!valid_symbols[T_NUMERIC_BULLET]) {
    return false;
  }

  bool parenthesized = false;
  if (scanner->lookahead == '(') {
    scanner->advance(scanner);
    parenthesized = true;
  }

  if (is_numeric_bullet(scanner->lookahead)) {
    return parse_inner_numeric_bullet(scanner, parenthesized);
  }

  return false;
}

static bool parse_inner_numeric_bullet(RSTScanner* scanner, bool parenthesized)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  if (!is_numeric_bullet(scanner->lookahead) || !valid_symbols[T_NUMERIC_BULLET]) {
    return false;
  }

  scanner->advance(scanner);
  int consumed_chars = 1;

  if (is_numeric_bullet_simple(scanner->previous)) {
    while (is_numeric_bullet_simple(scanner->lookahead) && scanner->lookahead != '#') {
      scanner->advance(scanner);
      consumed_chars++;
    }
  } else if (is_numeric_bullet_abc_lower(scanner->previous)) {
    if (is_numeric_bullet_roman_lower(scanner->previous)) {
      while (is_numeric_bullet_roman_lower(scanner->lookahead)) {
        scanner->advance(scanner);
        consumed_chars++;
      }
    }
  } else if (is_numeric_bullet_abc_upper(scanner->previous)) {
    if (is_numeric_bullet_roman_upper(scanner->previous)) {
      while (is_numeric_bullet_roman_upper(scanner->lookahead)) {
        scanner->advance(scanner);
        consumed_chars++;
      }
    }
  } else {
    return false;
  }

  if ((parenthesized && scanner->lookahead == ')')
      || (!parenthesized && (scanner->lookahead == '.' || scanner->lookahead == ')'))) {
    scanner->advance(scanner);
    consumed_chars++;
    consumed_chars += parenthesized ? 1 : 0;
    bool ok = parse_inner_list_element(scanner, consumed_chars, T_NUMERIC_BULLET);
    if (ok) {
      return true;
    }
  } else {
    if (is_abc(scanner->lookahead) && valid_symbols[T_STANDALONE_HYPERLINK]) {
      return parse_inner_standalone_hyperlink(scanner);
    }
    if (is_alphanumeric(scanner->lookahead) && valid_symbols[T_REFERENCE]) {
      return parse_reference(scanner);
    }
    if (valid_symbols[T_TEXT]) {
      lexer->markEnd(lexer);
      lexer->resultSymbol = T_TEXT;
      return true;
    }
    return false;
  }
  return parse_text(scanner, true);
}

static bool parse_explict_markup_start(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;

  if (scanner->lookahead != '.' || !valid_symbols[T_EXPLICIT_MARKUP_START]) {
    return false;
  }

  scanner->advance(scanner);

  if (scanner->lookahead != '.') {
    return false;
  }

  scanner->advance(scanner);

  bool ok = parse_inner_list_element(scanner, 2, T_EXPLICIT_MARKUP_START);
  if (ok) {
    return true;
  }

  return false;
}

static bool parse_inner_list_element(RSTScanner* scanner, int consumed_chars, enum TokenType token_type)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  if (!valid_symbols[token_type]) {
    return false;
  }

  if (is_space(scanner->lookahead)) {
    lexer->markEnd(lexer);
    lexer->resultSymbol = token_type;

    // Set indent level to the first non-whitespace char
    int indent = scanner->back(scanner) + consumed_chars + get_indent_level(scanner);

    // If it's an empty line and T_EXPLICIT_MARKUP_START, then it's an empty comment.
    // Empty comments don't consume any following indented text.
    if (is_newline(scanner->lookahead) && token_type == T_EXPLICIT_MARKUP_START) {
      bool is_empty = true;
      scanner->advance(scanner);
      while (!is_newline(scanner->lookahead)) {
        if (!is_space(scanner->lookahead)) {
          is_empty = false;
          break;
        }
        scanner->advance(scanner);
      }
      if (is_empty && valid_symbols[T_EMPTY_COMMENT]) {
        lexer->resultSymbol = T_EMPTY_COMMENT;
        return true;
      }
    } else if (token_type == T_EXPLICIT_MARKUP_START) {
      // Go to the next line.
      while (!is_newline(scanner->lookahead)) {
        scanner->advance(scanner);
      }
      scanner->advance(scanner);

      // The first non-empty line after the marker
      // determines the indentation of the body.
      while (true) {
        indent = get_indent_level(scanner);
        if (!is_newline(scanner->lookahead) || scanner->lookahead == CHAR_EOF) {
          break;
        }
        scanner->advance(scanner);
      }
      if (indent <= scanner->back(scanner)) {
        indent = scanner->back(scanner) + 1;
      }
    } else if (token_type == T_NUMERIC_BULLET) {
      // Check if the next line is an underline.
      // In that case, the list item is just a normal text from a title,
      // the underline must be at least as long as the title
      // https://github.com/stsewd/tree-sitter-rst/issues/30.

      // Go to the next line.
      consumed_chars = indent;
      while (!is_newline(scanner->lookahead)) {
        consumed_chars++;
        scanner->advance(scanner);
      }
      scanner->advance(scanner);

      // Check if that line is a valid underline.
      int32_t adornment = scanner->lookahead;
      int adornment_length = 0;
      if (is_adornment_char(adornment)) {
        while (true) {
          if (is_newline(scanner->lookahead)) {
            break;
          }
          if (scanner->lookahead != adornment) {
            adornment_length = -1;
            break;
          }
          adornment_length++;
          scanner->advance(scanner);
        }
      }
      if (adornment_length > 0 && adornment_length >= consumed_chars) {
        return parse_text(scanner, false);
      }
    }

    scanner->push(scanner, indent);
    return true;
  }

  return false;
}

static bool parse_field_mark(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  if (scanner->lookahead != ':' || !valid_symbols[T_FIELD_MARK]) {
    return false;
  }

  scanner->advance(scanner);
  lexer->markEnd(lexer);

  if (is_space(scanner->lookahead)) {
    return parse_text(scanner, true);
  }

  bool ok = parse_inner_field_mark(scanner);
  if (ok) {
    return true;
  }
  return parse_text(scanner, false);
}

static bool parse_inner_field_mark(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  if (!valid_symbols[T_FIELD_MARK]) {
    return false;
  }

  bool is_escaped = false;
  while (!is_newline(scanner->lookahead)) {
    if (scanner->lookahead == '/') {
      scanner->advance(scanner);
      is_escaped = true;
    } else {
      is_escaped = false;
    }

    if (scanner->lookahead == ':' && !is_space(scanner->previous) && !is_escaped) {
      scanner->advance(scanner);
      if (is_space(scanner->lookahead)) {
        break;
      }
    }

    scanner->advance(scanner);
  }

  if (scanner->previous == ':' && is_space(scanner->lookahead)) {
    lexer->resultSymbol = T_FIELD_MARK;
    return true;
  }
  return false;
}

static bool parse_field_mark_end(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  if (scanner->lookahead != ':' || !valid_symbols[T_FIELD_MARK_END]) {
    return false;
  }

  scanner->advance(scanner);
  lexer->markEnd(lexer);

  if (is_space(scanner->lookahead)) {
    // Consume all whitespaces.
    get_indent_level(scanner);
    // Go to the next line.
    while (!is_newline(scanner->lookahead)) {
      scanner->advance(scanner);
    }
    scanner->advance(scanner);

    // The first non-empty line after the field name marker
    // determines the indentation of the field body.
    int indent = 0;
    while (true) {
      indent = get_indent_level(scanner);
      if (!is_newline(scanner->lookahead) || scanner->lookahead == CHAR_EOF) {
        break;
      }
      scanner->advance(scanner);
    }
    if (indent > scanner->back(scanner)) {
      scanner->push(scanner, indent);
    } else {
      scanner->push(scanner, scanner->back(scanner) + 1);
    }

    lexer->resultSymbol = T_FIELD_MARK_END;
    return true;
  }

  return parse_text(scanner, false);
}

static bool parse_label(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  if (scanner->lookahead != '['
      || !(valid_symbols[T_FOOTNOTE_LABEL] || valid_symbols[T_CITATION_LABEL])) {
    return false;
  }
  scanner->advance(scanner);
  int type = parse_inner_label_name(scanner);
  if ((type == IM_CITATION_REFERENCE && valid_symbols[T_CITATION_LABEL])
      || (type == IM_FOOTNOTE_REFERENCE && valid_symbols[T_FOOTNOTE_LABEL])) {
    scanner->advance(scanner);
    if (is_space(scanner->lookahead)) {
      lexer->markEnd(lexer);
      if (type == IM_CITATION_REFERENCE) {
        lexer->resultSymbol = T_CITATION_LABEL;
      } else if (type == IM_FOOTNOTE_REFERENCE) {
        lexer->resultSymbol = T_FOOTNOTE_LABEL;
      }
      return true;
    }
  }

  return false;
}

static int parse_inner_label_name(RSTScanner* scanner)
{
  int type = -1;
  if (is_number(scanner->lookahead)) {
    while (is_number(scanner->lookahead)) {
      scanner->advance(scanner);
    }
    if (scanner->lookahead == ']') {
      type = IM_FOOTNOTE_REFERENCE;
    } else {
      if (parse_inner_alphanumeric_label(scanner)) {
        type = IM_CITATION_REFERENCE;
      }
    }
  } else if (scanner->lookahead == '*') {
    type = IM_FOOTNOTE_REFERENCE;
    scanner->advance(scanner);
  } else if (scanner->lookahead == '#') {
    scanner->advance(scanner);
    if (scanner->lookahead == ']') {
      type = IM_FOOTNOTE_REFERENCE;
    } else if (is_alphanumeric(scanner->lookahead)) {
      if (parse_inner_alphanumeric_label(scanner)) {
        type = IM_FOOTNOTE_REFERENCE;
      }
    }
  } else if (is_alphanumeric(scanner->lookahead)) {
    if (parse_inner_alphanumeric_label(scanner)) {
      type = IM_CITATION_REFERENCE;
    }
  } else {
    return -1;
  }

  if (scanner->lookahead == ']') {
    return type;
  }

  return -1;
}

static bool parse_inner_alphanumeric_label(RSTScanner* scanner)
{
  if (!(is_alphanumeric(scanner->lookahead)
          || is_internal_reference_char(scanner->lookahead))) {
    return false;
  }

  bool internal_symbol = false;
  while (is_alphanumeric(scanner->lookahead) || is_internal_reference_char(scanner->lookahead)) {
    if (is_internal_reference_char(scanner->lookahead)) {
      if (internal_symbol) {
        return false;
      }
      internal_symbol = true;
    } else {
      internal_symbol = false;
    }
    scanner->advance(scanner);
  }

  if (scanner->lookahead == ']') {
    return true;
  }

  return false;
}

static bool parse_target_name(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  if (scanner->lookahead != '_' || !valid_symbols[T_TARGET_NAME]) {
    return false;
  }

  scanner->advance(scanner);

  if (scanner->lookahead == '_') {
    scanner->advance(scanner);
  } else if (scanner->lookahead == '`') {
    // Find ending "`:".
    while (true) {
      if (scanner->lookahead == '`') {
        scanner->advance(scanner);
        if (scanner->lookahead == ':') {
          break;
        }
      }

      if (is_newline(scanner->lookahead)) {
        break;
      }

      scanner->advance(scanner);
    }
  } else {
    bool is_escaped = false;
    while (true) {
      if (scanner->lookahead == '\\') {
        scanner->advance(scanner);
        is_escaped = true;
      } else {
        is_escaped = false;
      }

      if (is_newline(scanner->lookahead)) {
        break;
      }

      if (scanner->lookahead == ':' && !is_escaped) {
        break;
      }
      scanner->advance(scanner);
    }
  }

  // check for ': '
  if (scanner->lookahead != ':') {
    return false;
  }

  scanner->advance(scanner);

  if (is_space(scanner->lookahead)) {
    lexer->markEnd(lexer);
    lexer->resultSymbol = T_TARGET_NAME;
    return true;
  }

  return false;
}

static bool parse_anonymous_target_mark(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  if (scanner->lookahead != '_' || !valid_symbols[T_ANONYMOUS_TARGET_MARK]) {
    return false;
  }

  scanner->advance(scanner);

  if (scanner->lookahead != '_') {
    return false;
  }

  scanner->advance(scanner);

  if (is_space(scanner->lookahead)) {
    lexer->markEnd(lexer);
    lexer->resultSymbol = T_ANONYMOUS_TARGET_MARK;
    return true;
  }

  return false;
}

static bool parse_directive_name(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  if (!is_alphanumeric(scanner->lookahead) || !valid_symbols[T_DIRECTIVE_NAME]) {
    return false;
  }

  scanner->advance(scanner);

  bool internal_symbol = false;
  bool keep_parsing = true;
  while (is_alphanumeric(scanner->lookahead)
      || is_internal_reference_char(scanner->lookahead)
      || (is_space(scanner->lookahead) && !is_newline(scanner->lookahead))) {
    // Directive names can have one (and only one) space before `::`.
    if (is_space(scanner->lookahead)) {
      lexer->markEnd(lexer);
      scanner->advance(scanner);
      scanner->advance(scanner);
      keep_parsing = false;
      break;
    }
    if (is_internal_reference_char(scanner->lookahead)) {
      if (internal_symbol) {
        break;
      }
      internal_symbol = true;
      lexer->markEnd(lexer);
    } else {
      internal_symbol = false;
    }
    scanner->advance(scanner);
  }

  if (scanner->lookahead != ':' || scanner->previous != ':') {
    return parse_text(scanner, keep_parsing);
  }
  scanner->advance(scanner);

  if (is_space(scanner->lookahead)) {
    lexer->resultSymbol = T_DIRECTIVE_NAME;
    return true;
  }

  return false;
}

static bool parse_substitution_mark(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  if (scanner->lookahead != '|' || !valid_symbols[T_SUBSTITUTION_MARK]) {
    return false;
  }

  scanner->advance(scanner);

  if (!is_space(scanner->lookahead)) {
    bool ok = parse_inner_inline_markup(scanner, IM_SUBSTITUTION_REFERENCE);
    if (ok
        && lexer->resultSymbol == T_SUBSTITUTION_REFERENCE
        && is_space(scanner->lookahead)
        && !is_newline(scanner->lookahead)) {
      lexer->resultSymbol = T_SUBSTITUTION_MARK;
      return true;
    }
  }
  return false;
}

static bool parse_literal_block_mark(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;

  if (scanner->lookahead != ':'
      || !(valid_symbols[T_LITERAL_INDENTED_BLOCK_MARK] || valid_symbols[T_LITERAL_QUOTED_BLOCK_MARK])) {
    return false;
  }

  scanner->advance(scanner);

  if (scanner->lookahead != ':') {
    if (valid_symbols[T_ROLE_NAME_PREFIX] || valid_symbols[T_ROLE_NAME_SUFFIX]) {
      return parse_inner_role(scanner);
    }
    return false;
  }

  scanner->advance(scanner);

  return parse_innner_literal_block_mark(scanner);
}

static bool parse_innner_literal_block_mark(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  if (!is_space(scanner->lookahead)
      || !(valid_symbols[T_LITERAL_INDENTED_BLOCK_MARK] || valid_symbols[T_LITERAL_QUOTED_BLOCK_MARK])) {
    return false;
  }

  lexer->markEnd(lexer);

  // Consume all whitespaces.
  while (is_space(scanner->lookahead) && !is_newline(scanner->lookahead)) {
    scanner->advance(scanner);
  }

  if (!is_newline(scanner->lookahead)) {
    return parse_text(scanner, false);
  }

  scanner->advance(scanner);

  // Make sure there is blank line
  while (!is_newline(scanner->lookahead)) {
    if (!is_space(scanner->lookahead)) {
      return false;
    }
    scanner->advance(scanner);
  }
  scanner->advance(scanner);

  // Skip all whitespaces and newlines and
  // get the indentation level of the first non-empty line.
  int indent = -1;
  while (scanner->lookahead != CHAR_EOF) {
    int local_indent = get_indent_level(scanner);
    if (!is_newline(scanner->lookahead)) {
      indent = local_indent;
      break;
    }
    scanner->advance(scanner);
  }

  // Literal blocks need to be indented, and quoted literal blocks
  // need to start with an adornment at the same indentation level.
  if (indent > scanner->back(scanner)) {
    scanner->push(scanner, scanner->back(scanner) + 1);
    lexer->resultSymbol = T_LITERAL_INDENTED_BLOCK_MARK;
  } else if (indent == scanner->back(scanner) && is_adornment_char(scanner->lookahead)) {
    lexer->resultSymbol = T_LITERAL_QUOTED_BLOCK_MARK;
  } else {
    return false;
  }
  if (!valid_symbols[lexer->resultSymbol]) {
    return false;
  }
  return true;
}

static bool parse_quoted_literal_block(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  if (!is_adornment_char(scanner->lookahead) || !valid_symbols[T_QUOTED_LITERAL_BLOCK]) {
    return false;
  }

  int32_t adornment = scanner->lookahead;
  int current_indent = scanner->back(scanner);

  while (true) {
    while (!is_newline(scanner->lookahead)) {
      scanner->advance(scanner);
    }
    lexer->markEnd(lexer);

    scanner->advance(scanner);

    // Check if it's an empty line or if the indentation was broken.
    int indent = get_indent_level(scanner);
    if (indent != current_indent || scanner->lookahead != adornment) {
      break;
    }

    if (scanner->lookahead != adornment) {
      return parse_text(scanner, false);
    }
  }
  lexer->resultSymbol = T_QUOTED_LITERAL_BLOCK;
  return true;
}

static bool parse_line_block_mark(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;

  if (scanner->lookahead != '|' || !valid_symbols[T_LINE_BLOCK_MARK]) {
    return false;
  }

  scanner->advance(scanner);

  if (is_space(scanner->lookahead)) {
    return parse_inner_list_element(scanner, 1, T_LINE_BLOCK_MARK);
  }

  return false;
}

static bool parse_attribution_mark(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;

  if (!is_attribution_mark(scanner->lookahead) || !valid_symbols[T_ATTRIBUTION_MARK]) {
    return false;
  }

  int consumed_chars = 0;
  if (scanner->lookahead == '-') {
    while (scanner->lookahead == '-') {
      consumed_chars++;
      scanner->advance(scanner);
    }

    if (consumed_chars < 2 || consumed_chars > 3) {
      return false;
    }
  } else {
    scanner->advance(scanner);
    consumed_chars++;
  }

  return parse_inner_list_element(scanner, consumed_chars, T_ATTRIBUTION_MARK);
}

static bool parse_doctest_block_mark(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  if (scanner->lookahead != '>' || !valid_symbols[T_DOCTEST_BLOCK_MARK]) {
    return false;
  }

  int consumed_chars = 0;
  while (scanner->lookahead == '>') {
    consumed_chars++;
    scanner->advance(scanner);
  }

  if (consumed_chars == 3 && is_space(scanner->lookahead)) {
    lexer->markEnd(lexer);
    lexer->resultSymbol = T_DOCTEST_BLOCK_MARK;
    return true;
  }
  return false;
}

static bool parse_inline_markup(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;
  scanner->advance(scanner);
  lexer->markEnd(lexer);

  unsigned type = 0;

  if (scanner->previous == '*' && scanner->lookahead == '*' && valid_symbols[T_STRONG]) {
    type = IM_STRONG;
  } else if (scanner->previous == '*' && valid_symbols[T_EMPHASIS]) {
    type = IM_EMPHASIS;
  } else if (scanner->previous == '`' && scanner->lookahead == '`' && valid_symbols[T_LITERAL]) {
    type = IM_LITERAL;
  } else if (scanner->previous == '`' && (valid_symbols[T_INTERPRETED_TEXT] || valid_symbols[T_INTERPRETED_TEXT_PREFIX] || valid_symbols[T_REFERENCE])) {
    type = IM_INTERPRETED_TEXT | IM_INTERPRETED_TEXT_PREFIX | IM_REFERENCE;
  } else if (scanner->previous == '|' && valid_symbols[T_SUBSTITUTION_REFERENCE]) {
    type = IM_SUBSTITUTION_REFERENCE;
  } else if (scanner->previous == '_' && scanner->lookahead == '`' && valid_symbols[T_INLINE_TARGET]) {
    type = IM_INLINE_TARGET;
  } else if (scanner->previous == '[' && (valid_symbols[T_FOOTNOTE_REFERENCE] || valid_symbols[T_CITATION_REFERENCE])) {
    type = IM_FOOTNOTE_REFERENCE | IM_CITATION_REFERENCE;
  }

  // Skip one char for tokens that start with a double char
  if (type & (IM_STRONG | IM_LITERAL | IM_INLINE_TARGET)) {
    scanner->advance(scanner);
  }

  // The next character can't be a white space
  if (is_space(scanner->lookahead)) {
    if (type & IM_EMPHASIS) {
      bool ok = parse_inner_list_element(scanner, 1, T_CHAR_BULLET);
      if (ok) {
        return true;
      }
    }
    if (valid_symbols[T_TEXT]) {
      lexer->markEnd(lexer);
      lexer->resultSymbol = T_TEXT;
      return true;
    }
    return false;
  }

  return parse_inner_inline_markup(scanner, type);
}

static bool parse_inner_inline_markup(RSTScanner* scanner, unsigned type)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  int consumed_chars = 0;
  bool word_found = false;
  bool is_escaped = false;

  if (type & IM_FOOTNOTE_REFERENCE || type & IM_CITATION_REFERENCE) {
    int final_type = parse_inner_label_name(scanner);
    if ((final_type == IM_FOOTNOTE_REFERENCE && type & IM_FOOTNOTE_REFERENCE)
        || (final_type == IM_CITATION_REFERENCE && type & IM_CITATION_REFERENCE)) {
      scanner->advance(scanner);
      if (scanner->lookahead == '_') {
        scanner->advance(scanner);
        if (is_space(scanner->lookahead) || is_end_char(scanner->lookahead)) {
          lexer->markEnd(lexer);
          if (final_type == IM_CITATION_REFERENCE) {
            lexer->resultSymbol = T_CITATION_REFERENCE;
          } else if (final_type == IM_FOOTNOTE_REFERENCE) {
            lexer->resultSymbol = T_FOOTNOTE_REFERENCE;
          }
          return true;
        }
      }
    }
    return parse_text(scanner, false);
  }

  while (scanner->lookahead != CHAR_EOF) {
    // Skip indentation
    if (is_newline(scanner->lookahead)) {
      if (!word_found) {
        word_found = true;
        lexer->markEnd(lexer);
      }
      scanner->advance(scanner);
      int indent = get_indent_level(scanner);
      if (indent != scanner->back(scanner) || is_newline(scanner->lookahead)) {
        break;
      }
    }

    // Skip escaped chars
    if (scanner->lookahead == '\\') {
      is_escaped = true;
      scanner->advance(scanner);
      if (is_newline(scanner->lookahead)) {
        break;
      }
    } else {
      is_escaped = false;
    }

    // Mark the end of the word if a space was found
    if (!word_found && is_space(scanner->lookahead)) {
      word_found = true;
      lexer->markEnd(lexer);
    }

    // Mark the end of the word if a start char was found
    if (!word_found && is_start_char(scanner->lookahead)) {
      word_found = true;
      lexer->markEnd(lexer);
    }

    // Check if it's a terminal character
    if (consumed_chars > 0 && !is_space(scanner->previous) && is_inline_markup_end_char(scanner->lookahead)
        // Literal is the only inline markup that doesn't care if the previous
        // char is '\'
        && (!is_escaped || (type & IM_LITERAL))) {
      scanner->advance(scanner);

      bool is_valid = true;
      bool advance = false;

      if ((type & IM_STRONG) && scanner->previous == '*' && scanner->lookahead == '*') {
        lexer->resultSymbol = T_STRONG;
        while (scanner->lookahead == '*') {
          scanner->advance(scanner);
          consumed_chars++;
        }
      } else if ((type & IM_EMPHASIS) && scanner->previous == '*') {
        lexer->resultSymbol = T_EMPHASIS;
      } else if ((type & IM_LITERAL) && scanner->previous == '`' && scanner->lookahead == '`') {
        lexer->resultSymbol = T_LITERAL;
        while (scanner->lookahead == '`') {
          scanner->advance(scanner);
          consumed_chars++;
        }
      } else if ((type & IM_INLINE_TARGET) && scanner->previous == '`') {
        lexer->resultSymbol = T_INLINE_TARGET;
      } else if ((type & IM_REFERENCE) && scanner->previous == '`' && scanner->lookahead == '_') {
        lexer->resultSymbol = T_REFERENCE;

        // Check for annonymous references
        scanner->advance(scanner);
        consumed_chars++;
        if (scanner->lookahead == '_') {
          advance = true;
        }
      } else if ((type & IM_INTERPRETED_TEXT || type & IM_INTERPRETED_TEXT_PREFIX) && scanner->previous == '`') {
        if (scanner->lookahead == ':' && type & IM_INTERPRETED_TEXT_PREFIX && valid_symbols[T_INTERPRETED_TEXT_PREFIX]) {
          lexer->markEnd(lexer);
          scanner->advance(scanner);
          bool ok = parse_role_name(scanner);
          if (ok) {
            lexer->resultSymbol = T_INTERPRETED_TEXT_PREFIX;
            return true;
          }
          if (valid_symbols[T_INTERPRETED_TEXT]) {
            lexer->resultSymbol = T_INTERPRETED_TEXT;
            return true;
          }
          is_valid = false;
        } else {
          lexer->resultSymbol = T_INTERPRETED_TEXT;
        }
      } else if ((type & IM_SUBSTITUTION_REFERENCE) && scanner->previous == '|') {
        lexer->resultSymbol = T_SUBSTITUTION_REFERENCE;
        // Substitution references can end with '__'.
        if (scanner->lookahead == '_') {
          scanner->advance(scanner);
          if (scanner->lookahead == '_') {
            advance = true;
          }
        }
      } else {
        is_valid = false;
      }

      if (advance) {
        scanner->advance(scanner);
        consumed_chars++;
      }

      // The next char should be a whitespace or an end char
      if (is_valid && (is_space(scanner->lookahead) || is_end_char(scanner->lookahead))) {
        lexer->markEnd(lexer);
        return true;
      }
    } else {
      scanner->advance(scanner);
    }

    consumed_chars++;
  }

  if (!word_found && is_newline(scanner->lookahead)) {
    return parse_text(scanner, true);
  }
  return parse_text(scanner, false);
}

static bool parse_reference(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;

  if (is_space(scanner->lookahead) || is_internal_reference_char(scanner->lookahead) || !valid_symbols[T_REFERENCE]) {
    return false;
  }
  scanner->advance(scanner);
  return parse_inner_reference(scanner);
}

static bool parse_inner_reference(RSTScanner* scanner)
{
  Lexer* lexer = scanner->lexer;

  bool internal_symbol = is_internal_reference_char(scanner->previous);
  bool is_word = false;
  while ((!is_space(scanner->lookahead) && !is_end_char(scanner->lookahead)) || is_internal_reference_char(scanner->lookahead)) {
    // Mark the end of the worl?d.
    if (is_start_char(scanner->lookahead) && !is_word) {
      is_word = true;
      lexer->markEnd(lexer);
    }
    if (is_internal_reference_char(scanner->lookahead)) {
      if (internal_symbol) {
        break;
      }
      internal_symbol = true;
    } else {
      internal_symbol = false;
    }
    scanner->advance(scanner);
  }

  // Only an anonymous reference can contain
  // and end with two consecutive '_'.
  if (scanner->lookahead == '_' && scanner->previous == '_') {
    scanner->advance(scanner);
  }

  if (scanner->previous == '_' && (is_space(scanner->lookahead) || is_end_char(scanner->lookahead))) {
    lexer->markEnd(lexer);
    lexer->resultSymbol = T_REFERENCE;
    return true;
  }

  return parse_text(scanner, !is_word);
}

static bool parse_standalone_hyperlink(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;

  if (!is_abc(scanner->lookahead) || !valid_symbols[T_STANDALONE_HYPERLINK]) {
    return false;
  }
  scanner->advance(scanner);
  return parse_inner_standalone_hyperlink(scanner);
}

static bool parse_inner_standalone_hyperlink(RSTScanner* scanner)
{
  Lexer* lexer = scanner->lexer;

  const unsigned MAX_SCHEMA_LEN = 20;
  char* schema = scanner_malloc(sizeof(char) * MAX_SCHEMA_LEN);
  unsigned consumed_chars = 0;

  // TODO: cast this more safely
  schema[consumed_chars++] = (char)scanner->previous;
  while (consumed_chars < MAX_SCHEMA_LEN) {
    if (!is_alphanumeric(scanner->lookahead)) {
      break;
    }
    // TODO: cast this more safely
    schema[consumed_chars++] = (char)scanner->lookahead;
    scanner->advance(scanner);
  }

  bool is_word = false;
  if (is_start_char(scanner->lookahead)) {
    lexer->markEnd(lexer);
  }

  bool is_valid = false;
  if (scanner->lookahead == ':') {
    is_valid = is_known_schema(schema, consumed_chars);
  } else if (scanner->lookahead == '@') {
    is_valid = true;
  }

  // Clean up
  free(schema);
  schema = NULL;

  if (!is_valid) {
    if ((!is_space(scanner->lookahead) && !is_end_char(scanner->lookahead)) || is_internal_reference_char(scanner->lookahead)) {
      return parse_inner_reference(scanner);
    }

    return parse_text(scanner, !is_word);
  }

  scanner->advance(scanner);

  if (scanner->lookahead == '/') {
    scanner->advance(scanner);
  } else if (!is_alphanumeric(scanner->lookahead)) {
    return parse_text(scanner, !is_word);
  }

  consumed_chars = 0;
  bool is_escaped = false;
  while (true) {
    lexer->markEnd(lexer);
    if (scanner->lookahead == '\\') {
      scanner->advance(scanner);
      is_escaped = true;
    } else {
      is_escaped = false;
    }
    if (is_invalid_uri_char(scanner->lookahead)) {
      break;
    }
    if (is_space(scanner->lookahead)
        || (is_end_char(scanner->lookahead) && !is_escaped && scanner->lookahead != '/')) {
      if (is_end_char(scanner->lookahead)) {
        lexer->markEnd(lexer);
        scanner->advance(scanner);
        if (!is_alphanumeric(scanner->lookahead)) {
          lexer->resultSymbol = T_STANDALONE_HYPERLINK;
          return true;
        }
      } else {
        break;
      }
    }
    scanner->advance(scanner);
    consumed_chars++;
  }

  if (consumed_chars > 0) {
    lexer->resultSymbol = T_STANDALONE_HYPERLINK;
    return true;
  }

  return parse_text(scanner, !is_word);
}

static bool parse_role(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  if (scanner->lookahead != ':'
      || (!valid_symbols[T_ROLE_NAME_SUFFIX] && !valid_symbols[T_ROLE_NAME_PREFIX])) {
    return false;
  }

  scanner->advance(scanner);

  // Mark the end of the word before going deeper.
  lexer->markEnd(lexer);

  if (is_space(scanner->lookahead) && valid_symbols[T_FIELD_MARK_END]) {
    // Consume all whitespaces.
    get_indent_level(scanner);
    lexer->markEnd(lexer);
    // Go to the next line
    while (!is_newline(scanner->lookahead)) {
      scanner->advance(scanner);
    }
    scanner->advance(scanner);

    // The first non-empty line after the field name marker
    // determines the indentation of the field body.
    int indent = 0;
    while (true) {
      indent = get_indent_level(scanner);
      if (!is_newline(scanner->lookahead) || scanner->lookahead == CHAR_EOF) {
        break;
      }
      scanner->advance(scanner);
    }
    if (indent > scanner->back(scanner)) {
      scanner->push(scanner, indent);
    } else {
      scanner->push(scanner, scanner->back(scanner) + 1);
    }

    lexer->resultSymbol = T_FIELD_MARK_END;
    return true;
  }

  if (is_alphanumeric(scanner->lookahead)) {
    bool ok = parse_inner_role(scanner);
    if (ok) {
      return true;
    }
  }

  return parse_text(scanner, false);
}

static bool parse_inner_role(RSTScanner* scanner)
{
  const bool* valid_symbols = scanner->valid_symbols;
  Lexer* lexer = scanner->lexer;

  if (!is_alphanumeric(scanner->lookahead)
      || (!valid_symbols[T_ROLE_NAME_SUFFIX] && !valid_symbols[T_ROLE_NAME_PREFIX])) {
    return false;
  }
  // Mark the end at the previous character (`:`),
  // so that the role name is not included in the T_FIELD_MARK token.
  lexer->markEnd(lexer);
  bool ok = parse_role_name(scanner);
  if (ok) {
    if (scanner->lookahead == '`' && valid_symbols[T_ROLE_NAME_PREFIX]) {
      lexer->markEnd(lexer);
      lexer->resultSymbol = T_ROLE_NAME_PREFIX;
      return true;
    }

    if (is_space(scanner->lookahead) && valid_symbols[T_FIELD_MARK]) {
      lexer->resultSymbol = T_FIELD_MARK;
      return true;
    }

    if ((is_space(scanner->lookahead) || is_end_char(scanner->lookahead))
        && valid_symbols[T_ROLE_NAME_SUFFIX]) {
      lexer->markEnd(lexer);
      lexer->resultSymbol = T_ROLE_NAME_SUFFIX;
      return true;
    }
  }
  if (valid_symbols[T_FIELD_MARK]) {
    ok = parse_inner_field_mark(scanner);
    if (ok) {
      return true;
    }
  }
  return false;
}

/// This function assumes the previous token was `:` and it's already consumed.
static bool parse_role_name(RSTScanner* scanner)
{
  if (!is_alphanumeric(scanner->lookahead)) {
    return false;
  }

  bool internal_symbol = true;
  while (is_alphanumeric(scanner->lookahead) || is_internal_reference_char(scanner->lookahead)) {
    if (is_internal_reference_char(scanner->lookahead)) {
      if (internal_symbol) {
        return false;
      }
      internal_symbol = true;
    } else {
      internal_symbol = false;
    }
    scanner->advance(scanner);
  }

  if (scanner->previous == ':') {
    return true;
  }

  return false;
}

/// Parse normal text.
///
/// Text nodes are separated by white spaces or a start char like `(`
static bool parse_text(RSTScanner* scanner, bool mark_end)
{
  Lexer* lexer = scanner->lexer;
  const bool* valid_symbols = scanner->valid_symbols;
  if (!valid_symbols[T_TEXT]) {
    return false;
  }

  if (is_start_char(scanner->lookahead)) {
    scanner->advance(scanner);
  } else {
    while (!is_space(scanner->lookahead)) {
      if (is_start_char(scanner->lookahead)) {
        break;
      }
      scanner->advance(scanner);
    }
  }

  if (mark_end) {
    lexer->markEnd(lexer);
  }
  lexer->resultSymbol = T_TEXT;
  return true;
}

// --- tokens.h already inlined above ---

/// Build a new `RSTScanner` object.
///
/// `destroy_rst_scanner` should be called to safely destroy this object.
static RSTScanner* new_rst_scanner()
{
  RSTScanner* scanner = scanner_malloc(sizeof(RSTScanner));

  scanner->advance = rst_scanner_advance;
  scanner->skip = rst_scanner_skip;

  scanner->indent_stack = scanner_malloc(sizeof(int) * RST_SCANNER_STACK_MAX_CAPACITY);
  scanner->length = 0;

  scanner->push = rst_scanner_push;
  scanner->pop = rst_scanner_pop;
  scanner->back = rst_scanner_back;

  scanner->serialize = rst_scanner_serialize;
  scanner->deserialize = rst_scanner_deserialize;
  scanner->scan = rst_scanner_scan;

  return scanner;
}

static void destroy_rst_scanner(RSTScanner* scanner)
{
  free(scanner->indent_stack);
  free(scanner);
}

static void rst_scanner_advance(RSTScanner* scanner)
{
  Lexer* lexer = scanner->lexer;
  scanner->previous = scanner->lookahead;
  lexer->advance(lexer, false);
  // Skip over the \r char in \r\n.
  if (lexer->lookahead == CHAR_CARRIAGE_RETURN) {
    lexer->advance(lexer, false);
  }
  scanner->lookahead = lexer->lookahead;
}

static void rst_scanner_skip(RSTScanner* scanner)
{
  Lexer* lexer = scanner->lexer;
  scanner->previous = scanner->lookahead;
  lexer->advance(lexer, true);
  scanner->lookahead = lexer->lookahead;
}

static void rst_scanner_push(RSTScanner* scanner, int value)
{
  if (scanner->length >= RST_SCANNER_STACK_MAX_CAPACITY) {
    return;
  }
  scanner->indent_stack[scanner->length++] = value;
}

static int rst_scanner_pop(RSTScanner* scanner)
{
  if (scanner->length <= 0) {
    return 0;
  }
  return scanner->indent_stack[--scanner->length];
}

static int rst_scanner_back(const RSTScanner* scanner)
{
  if (scanner->length <= 0) {
    return 0;
  }
  return scanner->indent_stack[scanner->length - 1];
}

static unsigned rst_scanner_serialize(RSTScanner* scanner, char* buffer)
{
  unsigned i = scanner->length;
  if (i > kSerializationBufferSize) {
    i = kSerializationBufferSize;
  }
  memcpy(buffer, scanner->indent_stack, i);
  return i;
}

static void rst_scanner_deserialize(RSTScanner* scanner, const char* buffer, unsigned length)
{
  if (buffer != NULL && length > 0) {
    memcpy((void*)buffer, scanner->indent_stack, length);
    scanner->length = length;
  } else {
    scanner->length = 0;
  }
}

static bool rst_scanner_scan(RSTScanner* scanner)
{
  Lexer* lexer = scanner->lexer;
  const bool* valid_symbols = scanner->valid_symbols;
  int32_t current = lexer->lookahead;

  // If all valid symbols are true, tree-sitter is in correction mode,
  // we fallback to parse the content as a text node.
  // TODO: We don't want to parse anything in this case,
  // we should move the text node parsing to JS.
  if (valid_symbols[T_INVALID_TOKEN]) {
    if (!is_space(current) && valid_symbols[T_TEXT]) {
      return parse_text(scanner, true);
    }
    return false;
  }

  if (is_adornment_char(current)
      && (valid_symbols[T_OVERLINE] || valid_symbols[T_TRANSITION])) {
    return parse_overline(scanner);
  }

  if (is_adornment_char(current)
      && (valid_symbols[T_UNDERLINE] || valid_symbols[T_TRANSITION])) {
    return parse_underline(scanner);
  }

  if (is_adornment_char(current) && valid_symbols[T_QUOTED_LITERAL_BLOCK]) {
    return parse_quoted_literal_block(scanner);
  }

  if (current == '.' && valid_symbols[T_EXPLICIT_MARKUP_START]) {
    return parse_explict_markup_start(scanner);
  }

  if (is_attribution_mark(current) && valid_symbols[T_ATTRIBUTION_MARK]) {
    return parse_attribution_mark(scanner);
  }

  if (current == '['
      && (valid_symbols[T_FOOTNOTE_LABEL] || valid_symbols[T_CITATION_LABEL])) {
    return parse_label(scanner);
  }

  if (current == '_' && valid_symbols[T_TARGET_NAME]) {
    return parse_target_name(scanner);
  }

  if (current == '_' && valid_symbols[T_ANONYMOUS_TARGET_MARK]) {
    return parse_anonymous_target_mark(scanner);
  }

  if (current == '|' && valid_symbols[T_SUBSTITUTION_MARK]) {
    return parse_substitution_mark(scanner);
  }

  if (current == '|' && valid_symbols[T_LINE_BLOCK_MARK]) {
    return parse_line_block_mark(scanner);
  }

  if (current == '>' && valid_symbols[T_DOCTEST_BLOCK_MARK]) {
    return parse_doctest_block_mark(scanner);
  }

  if (is_alphanumeric(current) && valid_symbols[T_DIRECTIVE_NAME]) {
    return parse_directive_name(scanner);
  }

  if (is_inline_markup_start_char(current)
      && (valid_symbols[T_EMPHASIS]
          || valid_symbols[T_STRONG]
          || valid_symbols[T_INTERPRETED_TEXT]
          || valid_symbols[T_INTERPRETED_TEXT_PREFIX]
          || valid_symbols[T_LITERAL]
          || valid_symbols[T_SUBSTITUTION_REFERENCE]
          || valid_symbols[T_INLINE_TARGET]
          || valid_symbols[T_FOOTNOTE_REFERENCE]
          || valid_symbols[T_CITATION_REFERENCE]
          || valid_symbols[T_REFERENCE])) {
    return parse_inline_markup(scanner);
  }

  if ((is_numeric_bullet(current) || current == '(')
      && valid_symbols[T_NUMERIC_BULLET]) {
    return parse_numeric_bullet(scanner);
  }

  if (is_char_bullet(current) && valid_symbols[T_CHAR_BULLET]) {
    return parse_char_bullet(scanner);
  }

  if (current == ':' && (valid_symbols[T_LITERAL_INDENTED_BLOCK_MARK] || valid_symbols[T_LITERAL_QUOTED_BLOCK_MARK])) {
    return parse_literal_block_mark(scanner);
  }

  if (current == ':' && (valid_symbols[T_ROLE_NAME_PREFIX] || valid_symbols[T_ROLE_NAME_SUFFIX])) {
    return parse_role(scanner);
  }

  if (current == ':' && valid_symbols[T_FIELD_MARK]) {
    return parse_field_mark(scanner);
  }

  if (current == ':' && valid_symbols[T_FIELD_MARK_END]) {
    return parse_field_mark_end(scanner);
  }

  if (is_abc(current) && valid_symbols[T_STANDALONE_HYPERLINK]) {
    return parse_standalone_hyperlink(scanner);
  }

  if (!is_space(current)
      && !is_internal_reference_char(current)
      && !is_start_char(current)
      && !is_end_char(current)
      && valid_symbols[T_REFERENCE]) {
    return parse_reference(scanner);
  }

  if (!is_space(current) && valid_symbols[T_TEXT]) {
    return parse_text(scanner, true);
  }

  if (is_space(current)) {
    return parse_indent(scanner);
  }

  return false;
}

// --- tokens.h already inlined above ---

static void* Create()
{
  return new_rst_scanner();
}

static void Destroy(void* payload_)
{
    VoidPtr payload{payload_};
  destroy_rst_scanner(payload);
}

static unsigned Serialize(
    void* payload_,
    char* buffer)
{
    VoidPtr payload{payload_};
  RSTScanner* scanner = payload;
  return scanner->serialize(scanner, buffer);
}

static void Deserialize(
    void* payload_,
    const char* buffer,
    unsigned length)
{
    VoidPtr payload{payload_};
  RSTScanner* scanner = payload;
  scanner->deserialize(scanner, buffer, length);
}

static bool Scan(
    void* payload_,
    Lexer* lexer,
    const bool* valid_symbols)
{
    VoidPtr payload{payload_};
  RSTScanner* scanner = (RSTScanner*)payload;
  scanner->lexer = lexer;
  scanner->valid_symbols = valid_symbols;
  scanner->lookahead = lexer->lookahead;
  scanner->previous = lexer->lookahead;
  return scanner->scan(scanner);
}

extern const ned::editor::parse::ScannerVTable kScanner = {Create, Destroy, Scan, Serialize, Deserialize};

} // namespace ned::editor::languages::scanners::rst
