cmake_minimum_required(VERSION 3.20)
function(foo x)
  if (x)
    message("a")
  elseif(y)
    message("b")
  else()
    message("c")
  endif()
  foreach(i IN LISTS l)
  endforeach()
  while(x)
  endwhile()
endfunction()
macro(bar)
endmacro()
