#include "Editor/CliOptions.h"

#include <CLI/CLI.hpp>

#include "NedVersion.h" // generated by CMake from Source/Version.h.in

namespace ned::editor {

void BuildCli(CLI::App& app, CliArgs& args) {
    // startup-mode-unification follow-up: one CLI::App owns every top-level
    // flag ned recognizes, --lsp-broker/--lsp-broker-stop included --
    // previously each was a hand-rolled `argv[1] == "..."` check run
    // *before* any real parsing, so `ned --help` never documented them.
    // They stay plain flags on this one App rather than becoming CLI11
    // subcommands specifically to keep the exact existing invocations
    // (`ned --lsp-broker`, notably self-exec'd by
    // Lsp/BrokerConnect.cpp, and documented as a systemd ExecStart
    // line) working unchanged -- a subcommand would mean `ned lsp-broker`
    // instead, a real breaking syntax change for no behavioral gain here.
    // ->excludes() catches the nonsensical case of passing more than one
    // of the three as a real CLI11 error instead of silently letting
    // whichever this code happened to check first win.
    app.description("Ned -- a terminal-based, Janet-scriptable text editor.");

    // The version reported here is CMakeLists.txt's own project(Ned VERSION
    // ...), routed through the generated NedVersion.h, so there is exactly one
    // place to bump. Printed as "ned <version>" rather than a bare number
    // because this is what a bug report gets pasted from.
    app.set_version_flag("--version", std::string("ned ") + Ned::kVersion,
                         "Print ned's version and exit");

    CLI::Option* lspBrokerOpt =
        app.add_flag("--lsp-broker", args.lspBroker, "Run the headless LSP broker daemon and exit")
            ->group(kStartupModesGroup);
    app.add_flag("--lsp-broker-stop", args.lspBrokerStop, "Stop a running LSP broker daemon and exit")
        ->excludes(lspBrokerOpt)
        ->group(kStartupModesGroup);
    app.add_flag("--foreground", args.foreground,
                 "Run the LSP broker daemon in the foreground, never self-exiting when idle -- for a systemd "
                 "--user service (see Packaging/systemd/ned-server.service) or any other real process supervisor. "
                 "An ordinary broker already holding the socket is shut down first and waited for; a second "
                 "--foreground instance refuses to start, since restarting the service is what a supervisor is for")
        ->excludes(lspBrokerOpt)
        ->group(kStartupModesGroup);
    app.add_option("--mcp-stdio-relay", args.mcpStdioRelaySocketPath,
                   "Relay stdio to a running ned process's ACP MCP bridge socket, then exit (spawned by an ACP agent, not meant to be run by hand)")
        ->excludes(lspBrokerOpt)
        ->group(kStartupModesGroup);
    app.add_flag("--format", args.format,
                 "Format the given files headlessly and exit (External formatter, falling back to a native "
                 "per-language reindent -- no LSP tier, no init.janet; format.janet only)")
        ->excludes(lspBrokerOpt)
        ->group(kStartupModesGroup);
    app.add_flag("--force-huge", args.forceHuge,
                 "With --format, reindent a file over the huge-file threshold via the lexical streaming engine "
                 "(Native reindent only -- no external formatter, no space/break/wrap/blank rules) instead of "
                 "skipping it")
        ->needs("--format");
    app.add_flag("--compile-language", args.compileLanguage,
                 "Compile each given language directory's grammar.janet to its parse tables (written as `tables` "
                 "beside it) and exit -- what the build runs for every bundled language, and the authoring loop "
                 "for a hand-written grammar")
        ->excludes(lspBrokerOpt)
        ->group(kStartupModesGroup);
    app.add_option("-o,--output", args.compileOutput, "With --compile-language (or as ned-langc) and a single language, write the tables to this file instead");
    app.add_flag("--import-language", args.importLanguage,
                 "Turn a tree-sitter grammar repository (a git URL or a checkout) into a ned language package: grammar.janet, "
                 "upstream queries, corpus, staged scanner, and a language.janet skeleton -- then compile it and run its corpus")
        ->excludes(lspBrokerOpt)
        ->group(kStartupModesGroup);
    app.add_option("--name", args.importName, "With --import-language: the language name (default: the grammar's own)");
    app.add_option("--subdir", args.importSubdir, "With --import-language: the grammar's directory inside a multi-grammar repository");
    app.add_option("--ref", args.importRef, "With --import-language and a git URL: the tag, branch or full commit hash to clone");
    app.add_option("--into", args.importInto, "With --import-language: the languages root to write the package under (default: $XDG_CONFIG_HOME/ned/languages)");
    app.add_flag("--test-language", args.testLanguage, "Run each given language package's corpus against its grammar and exit")
        ->excludes(lspBrokerOpt)
        ->group(kStartupModesGroup);
    app.add_flag("--bless", args.bless, "With --test-language: rewrite each failing case's expected tree to what the grammar parses now");
    app.add_flag("--force-binary", args.forceBinary,
                 "Open files that look binary anyway, without an interactive confirmation");
    app.add_flag("--no-restore", args.noRestore,
                 "Don't restore the project's saved session (open buffers, breakpoints, sidebar state)");
    app.add_flag("--transient", args.transient,
                 "Store nothing about this run: no project session (neither restored nor saved), no save-place, "
                 "no recent-files entry, no persistent undo, no backups. For running ned as another tool's "
                 "$EDITOR -- it is applied automatically for a file a version control system names (git's "
                 "COMMIT_EDITMSG and friends, hg, svn, jj, fossil)");
    app.add_flag("--no-transient", args.noTransient,
                 "Record this run normally even if the file opened is one a version control system names -- the "
                 "override for --transient's own automatic detection");
    app.add_option("--keymap-style", args.keymapStyle,
                   "Start with this keybinding convention: \"emacs\" (default), \"vim\", or \"modern\" (the same "
                   "setting ned/set-keymap-style controls; applied after init.janet loads, so this flag wins over "
                   "any ned/set-keymap-style call there)")
        ->check(CLI::IsMember({"emacs", "vim", "modern"}));
    app.add_option("paths", args.paths, "Files or directories to open");
}

} // namespace ned::editor
