// GENERATED by Tests/ImprintTest.cpp -- do not edit by hand.
//
// Regenerate with:  NED_BLESS_IMPRINT=1 ./build/ned_tests "[Imprint]"
// See Editor/ImprintTables.h for why this is checked in rather than
// derived at build time, and what guards it against going stale.

#include "Editor/ImprintTables.h"

namespace ned::editor::imprint {

namespace {

struct Entry {
    std::string_view node;
    DelimiterKind    kind;
    bool             openerIsFirst;
    bool             listLikeInterior;
};

constexpr Entry kC[] = {
    {"abstract_array_declarator", DelimiterKind::Bracket, false, true},
    {"abstract_parenthesized_declarator", DelimiterKind::Bracket, true, true},
    {"alignas_qualifier", DelimiterKind::Bracket, false, true},
    {"argument_list", DelimiterKind::Bracket, true, true},
    {"array_declarator", DelimiterKind::Bracket, false, true},
    {"array_field_declarator", DelimiterKind::Bracket, false, true},
    {"array_type_declarator", DelimiterKind::Bracket, false, true},
    {"attribute_specifier", DelimiterKind::Bracket, false, false},
    {"compound_statement", DelimiterKind::Bracket, true, true},
    {"declaration_list", DelimiterKind::Bracket, true, true},
    {"enumerator_list", DelimiterKind::Bracket, true, true},
    {"field_declaration_list", DelimiterKind::Bracket, true, true},
    {"generic_expression", DelimiterKind::Bracket, false, false},
    {"gnu_asm_expression", DelimiterKind::Bracket, false, true},
    {"gnu_asm_input_operand", DelimiterKind::Bracket, false, false},
    {"gnu_asm_output_operand", DelimiterKind::Bracket, false, false},
    {"initializer_list", DelimiterKind::Bracket, true, true},
    {"macro_type_specifier", DelimiterKind::Bracket, false, false},
    {"ms_declspec_modifier", DelimiterKind::Bracket, false, false},
    {"parameter_list", DelimiterKind::Bracket, true, true},
    {"parenthesized_declarator", DelimiterKind::Bracket, true, true},
    {"parenthesized_expression", DelimiterKind::Bracket, true, true},
    {"parenthesized_field_declarator", DelimiterKind::Bracket, true, true},
    {"parenthesized_type_declarator", DelimiterKind::Bracket, true, true},
    {"preproc_argument_list", DelimiterKind::Bracket, true, true},
    {"preproc_defined", DelimiterKind::Bracket, false, false},
    {"preproc_parenthesized_expression", DelimiterKind::Bracket, true, false},
    {"subscript_designator", DelimiterKind::Bracket, true, false},
    {"subscript_expression", DelimiterKind::Bracket, false, false},
    {"subscript_range_designator", DelimiterKind::Bracket, true, false},
};

constexpr Entry kClojure[] = {
    {"anon_fn_lit", DelimiterKind::Bracket, false, true},
    {"list_lit", DelimiterKind::Bracket, false, true},
    {"map_lit", DelimiterKind::Bracket, false, true},
    {"ns_map_lit", DelimiterKind::Bracket, false, true},
    {"read_cond_lit", DelimiterKind::Bracket, false, true},
    {"set_lit", DelimiterKind::Bracket, false, true},
    {"splicing_read_cond_lit", DelimiterKind::Bracket, false, true},
    {"vec_lit", DelimiterKind::Bracket, false, true},
};

constexpr Entry kCpp[] = {
    {"abstract_array_declarator", DelimiterKind::Bracket, false, true},
    {"abstract_parenthesized_declarator", DelimiterKind::Bracket, true, true},
    {"alignas_qualifier", DelimiterKind::Bracket, false, true},
    {"argument_list", DelimiterKind::Bracket, true, true},
    {"array_declarator", DelimiterKind::Bracket, false, true},
    {"array_field_declarator", DelimiterKind::Bracket, false, true},
    {"array_type_declarator", DelimiterKind::Bracket, false, true},
    {"attribute_specifier", DelimiterKind::Bracket, false, false},
    {"compound_statement", DelimiterKind::Bracket, true, true},
    {"condition_clause", DelimiterKind::Bracket, true, true},
    {"declaration_list", DelimiterKind::Bracket, true, true},
    {"decltype", DelimiterKind::Bracket, false, false},
    {"decltype_auto", DelimiterKind::Bracket, false, false},
    {"enumerator_list", DelimiterKind::Bracket, true, true},
    {"explicit_function_specifier", DelimiterKind::Bracket, false, false},
    {"field_declaration_list", DelimiterKind::Bracket, true, true},
    {"fold_expression", DelimiterKind::Bracket, true, true},
    {"generic_expression", DelimiterKind::Bracket, false, false},
    {"gnu_asm_expression", DelimiterKind::Bracket, false, true},
    {"gnu_asm_input_operand", DelimiterKind::Bracket, false, false},
    {"gnu_asm_output_operand", DelimiterKind::Bracket, false, false},
    {"initializer_list", DelimiterKind::Bracket, true, true},
    {"lambda_capture_specifier", DelimiterKind::Bracket, true, true},
    {"macro_type_specifier", DelimiterKind::Bracket, false, false},
    {"ms_declspec_modifier", DelimiterKind::Bracket, false, false},
    {"new_declarator", DelimiterKind::Bracket, true, false},
    {"noexcept", DelimiterKind::Bracket, false, true},
    {"parameter_list", DelimiterKind::Bracket, true, true},
    {"parenthesized_declarator", DelimiterKind::Bracket, true, true},
    {"parenthesized_expression", DelimiterKind::Bracket, true, true},
    {"parenthesized_field_declarator", DelimiterKind::Bracket, true, true},
    {"parenthesized_type_declarator", DelimiterKind::Bracket, true, true},
    {"preproc_argument_list", DelimiterKind::Bracket, true, true},
    {"preproc_defined", DelimiterKind::Bracket, false, false},
    {"preproc_parenthesized_expression", DelimiterKind::Bracket, true, false},
    {"requirement_seq", DelimiterKind::Bracket, true, true},
    {"requires_clause", DelimiterKind::Bracket, false, false},
    {"requires_parameter_list", DelimiterKind::Bracket, true, true},
    {"structured_binding_declarator", DelimiterKind::Bracket, true, false},
    {"subscript_argument_list", DelimiterKind::Bracket, true, true},
    {"subscript_designator", DelimiterKind::Bracket, true, false},
    {"subscript_range_designator", DelimiterKind::Bracket, true, false},
};

constexpr Entry kCsharp[] = {
    {"accessor_list", DelimiterKind::Bracket, true, true},
    {"anonymous_object_creation_expression", DelimiterKind::Bracket, false, true},
    {"argument_list", DelimiterKind::Bracket, true, true},
    {"array_rank_specifier", DelimiterKind::Bracket, true, true},
    {"attribute_argument_list", DelimiterKind::Bracket, true, true},
    {"attribute_list", DelimiterKind::Bracket, true, true},
    {"block", DelimiterKind::Bracket, true, true},
    {"bracketed_argument_list", DelimiterKind::Bracket, true, true},
    {"bracketed_parameter_list", DelimiterKind::Bracket, true, true},
    {"calling_convention", DelimiterKind::Bracket, false, false},
    {"catch_declaration", DelimiterKind::Bracket, true, true},
    {"catch_filter_clause", DelimiterKind::Bracket, false, false},
    {"checked_expression", DelimiterKind::Bracket, false, false},
    {"collection_expression", DelimiterKind::Bracket, true, true},
    {"constructor_constraint", DelimiterKind::Bracket, false, false},
    {"declaration_list", DelimiterKind::Bracket, true, true},
    {"default_expression", DelimiterKind::Bracket, false, false},
    {"enum_member_declaration_list", DelimiterKind::Bracket, true, true},
    {"function_pointer_type", DelimiterKind::Bracket, false, true},
    {"global_attribute", DelimiterKind::Bracket, true, true},
    {"initializer_expression", DelimiterKind::Bracket, true, true},
    {"interpolation", DelimiterKind::Indent, true, true},
    {"list_pattern", DelimiterKind::Bracket, true, true},
    {"makeref_expression", DelimiterKind::Bracket, false, false},
    {"namespace_declaration", DelimiterKind::Indent, true, true},
    {"parameter_list", DelimiterKind::Bracket, true, true},
    {"parenthesized_expression", DelimiterKind::Bracket, true, false},
    {"parenthesized_pattern", DelimiterKind::Bracket, true, false},
    {"parenthesized_variable_designation", DelimiterKind::Bracket, true, true},
    {"positional_pattern_clause", DelimiterKind::Bracket, true, true},
    {"preproc_parenthesized_expression", DelimiterKind::Bracket, true, false},
    {"property_pattern_clause", DelimiterKind::Bracket, true, true},
    {"raw_string_literal", DelimiterKind::Indent, true, true},
    {"reftype_expression", DelimiterKind::Bracket, false, false},
    {"refvalue_expression", DelimiterKind::Bracket, false, false},
    {"sizeof_expression", DelimiterKind::Bracket, false, false},
    {"switch_body", DelimiterKind::Bracket, true, true},
    {"switch_expression", DelimiterKind::Bracket, false, true},
    {"tuple_expression", DelimiterKind::Bracket, true, false},
    {"tuple_pattern", DelimiterKind::Bracket, true, false},
    {"tuple_type", DelimiterKind::Bracket, true, false},
    {"type_argument_list", DelimiterKind::Bracket, true, true},
    {"type_parameter_list", DelimiterKind::Bracket, true, false},
    {"typeof_expression", DelimiterKind::Bracket, false, false},
    {"with_expression", DelimiterKind::Bracket, false, true},
};

constexpr Entry kGo[] = {
    {"argument_list", DelimiterKind::Bracket, true, true},
    {"block", DelimiterKind::Bracket, true, true},
    {"expression_switch_statement", DelimiterKind::Bracket, false, true},
    {"field_declaration_list", DelimiterKind::Bracket, true, true},
    {"import_spec_list", DelimiterKind::Bracket, true, true},
    {"index_expression", DelimiterKind::Bracket, false, false},
    {"interface_type", DelimiterKind::Bracket, false, true},
    {"literal_value", DelimiterKind::Bracket, true, true},
    {"parameter_list", DelimiterKind::Bracket, true, true},
    {"parenthesized_expression", DelimiterKind::Bracket, true, false},
    {"parenthesized_type", DelimiterKind::Bracket, true, false},
    {"select_statement", DelimiterKind::Bracket, false, true},
    {"slice_expression", DelimiterKind::Bracket, false, true},
    {"special_argument_list", DelimiterKind::Bracket, true, true},
    {"type_arguments", DelimiterKind::Bracket, true, true},
    {"type_assertion_expression", DelimiterKind::Bracket, false, false},
    {"type_conversion_expression", DelimiterKind::Bracket, false, true},
    {"type_instantiation_expression", DelimiterKind::Bracket, false, true},
    {"type_parameter_list", DelimiterKind::Bracket, true, true},
    {"type_switch_statement", DelimiterKind::Bracket, false, true},
    {"var_spec_list", DelimiterKind::Bracket, true, true},
};

constexpr Entry kJava[] = {
    {"annotation_argument_list", DelimiterKind::Bracket, true, true},
    {"annotation_type_body", DelimiterKind::Bracket, true, true},
    {"argument_list", DelimiterKind::Bracket, true, true},
    {"array_access", DelimiterKind::Bracket, false, false},
    {"array_initializer", DelimiterKind::Bracket, true, true},
    {"block", DelimiterKind::Bracket, true, true},
    {"class_body", DelimiterKind::Bracket, true, true},
    {"constructor_body", DelimiterKind::Bracket, true, true},
    {"dimensions_expr", DelimiterKind::Bracket, false, false},
    {"element_value_array_initializer", DelimiterKind::Bracket, true, true},
    {"enum_body", DelimiterKind::Bracket, true, true},
    {"formal_parameters", DelimiterKind::Bracket, true, true},
    {"inferred_parameters", DelimiterKind::Bracket, true, false},
    {"interface_body", DelimiterKind::Bracket, true, true},
    {"module_body", DelimiterKind::Bracket, true, true},
    {"parenthesized_expression", DelimiterKind::Bracket, true, false},
    {"record_pattern_body", DelimiterKind::Bracket, true, true},
    {"resource_specification", DelimiterKind::Bracket, true, true},
    {"switch_block", DelimiterKind::Bracket, true, true},
    {"type_arguments", DelimiterKind::Bracket, true, true},
    {"type_parameters", DelimiterKind::Bracket, true, false},
};

constexpr Entry kJavascript[] = {
    {"arguments", DelimiterKind::Bracket, true, true},
    {"array", DelimiterKind::Bracket, true, true},
    {"array_pattern", DelimiterKind::Bracket, true, true},
    {"class_body", DelimiterKind::Bracket, true, true},
    {"computed_property_name", DelimiterKind::Bracket, true, false},
    {"export_clause", DelimiterKind::Bracket, true, true},
    {"formal_parameters", DelimiterKind::Bracket, true, true},
    {"jsx_expression", DelimiterKind::Bracket, true, true},
    {"jsx_opening_element", DelimiterKind::Bracket, true, true},
    {"named_imports", DelimiterKind::Bracket, true, true},
    {"object", DelimiterKind::Bracket, true, true},
    {"object_pattern", DelimiterKind::Bracket, true, true},
    {"parenthesized_expression", DelimiterKind::Bracket, true, false},
    {"statement_block", DelimiterKind::Bracket, true, true},
    {"subscript_expression", DelimiterKind::Bracket, false, false},
    {"switch_body", DelimiterKind::Bracket, true, true},
};

constexpr Entry kJson[] = {
    {"array", DelimiterKind::Bracket, true, true},
    {"object", DelimiterKind::Bracket, true, true},
};

constexpr Entry kKotlin[] = {
    {"anonymous_initializer", DelimiterKind::Bracket, false, true},
    {"catch_block", DelimiterKind::Bracket, false, true},
    {"class_body", DelimiterKind::Bracket, true, true},
    {"collection_literal", DelimiterKind::Bracket, true, true},
    {"control_structure_body", DelimiterKind::Bracket, true, true},
    {"do_while_statement", DelimiterKind::Bracket, false, false},
    {"enum_class_body", DelimiterKind::Bracket, true, true},
    {"finally_block", DelimiterKind::Bracket, false, true},
    {"for_statement", DelimiterKind::Bracket, false, true},
    {"function_body", DelimiterKind::Bracket, true, true},
    {"function_type_parameters", DelimiterKind::Bracket, true, true},
    {"function_value_parameters", DelimiterKind::Bracket, true, true},
    {"import_list", DelimiterKind::Indent, true, true},
    {"indexing_suffix", DelimiterKind::Bracket, true, false},
    {"lambda_literal", DelimiterKind::Bracket, true, true},
    {"multi_variable_declaration", DelimiterKind::Bracket, true, false},
    {"parameters_with_optional_type", DelimiterKind::Bracket, true, false},
    {"parenthesized_expression", DelimiterKind::Bracket, true, false},
    {"parenthesized_type", DelimiterKind::Bracket, true, true},
    {"parenthesized_user_type", DelimiterKind::Bracket, true, true},
    {"primary_constructor", DelimiterKind::Bracket, false, true},
    {"secondary_constructor", DelimiterKind::Bracket, false, true},
    {"string_literal", DelimiterKind::Indent, true, true},
    {"super_expression", DelimiterKind::Bracket, false, true},
    {"type_arguments", DelimiterKind::Bracket, true, false},
    {"type_parameters", DelimiterKind::Bracket, true, false},
    {"value_arguments", DelimiterKind::Bracket, true, true},
    {"when_expression", DelimiterKind::Bracket, false, true},
    {"when_subject", DelimiterKind::Bracket, true, true},
};

constexpr Entry kPython[] = {
    {"argument_list", DelimiterKind::Bracket, true, true},
    {"block", DelimiterKind::Indent, true, true},
    {"class_pattern", DelimiterKind::Bracket, false, true},
    {"decorator", DelimiterKind::Indent, true, true},
    {"dict_pattern", DelimiterKind::Bracket, true, true},
    {"dictionary", DelimiterKind::Bracket, true, true},
    {"dictionary_comprehension", DelimiterKind::Bracket, true, true},
    {"generator_expression", DelimiterKind::Bracket, true, true},
    {"interpolation", DelimiterKind::Bracket, true, true},
    {"keyword_pattern", DelimiterKind::Bracket, false, true},
    {"list", DelimiterKind::Bracket, true, true},
    {"list_comprehension", DelimiterKind::Bracket, true, true},
    {"list_pattern", DelimiterKind::Bracket, true, true},
    {"parameters", DelimiterKind::Bracket, true, true},
    {"parenthesized_expression", DelimiterKind::Bracket, true, true},
    {"parenthesized_list_splat", DelimiterKind::Bracket, true, true},
    {"set", DelimiterKind::Bracket, true, true},
    {"set_comprehension", DelimiterKind::Bracket, true, true},
    {"string", DelimiterKind::Indent, true, true},
    {"subscript", DelimiterKind::Bracket, false, true},
    {"tuple", DelimiterKind::Bracket, true, true},
    {"tuple_pattern", DelimiterKind::Bracket, true, true},
    {"type_parameter", DelimiterKind::Bracket, true, true},
};

constexpr Entry kRust[] = {
    {"arguments", DelimiterKind::Bracket, true, true},
    {"array_expression", DelimiterKind::Bracket, true, true},
    {"array_type", DelimiterKind::Bracket, true, true},
    {"attribute_item", DelimiterKind::Bracket, false, false},
    {"block", DelimiterKind::Bracket, false, true},
    {"bracketed_type", DelimiterKind::Bracket, true, true},
    {"declaration_list", DelimiterKind::Bracket, true, true},
    {"delim_token_tree", DelimiterKind::Bracket, true, true},
    {"enum_variant_list", DelimiterKind::Bracket, true, true},
    {"field_declaration_list", DelimiterKind::Bracket, true, true},
    {"field_initializer_list", DelimiterKind::Bracket, true, true},
    {"for_lifetimes", DelimiterKind::Bracket, false, true},
    {"index_expression", DelimiterKind::Bracket, false, false},
    {"inner_attribute_item", DelimiterKind::Bracket, false, false},
    {"match_block", DelimiterKind::Bracket, true, true},
    {"ordered_field_declaration_list", DelimiterKind::Bracket, true, true},
    {"parameters", DelimiterKind::Bracket, true, true},
    {"parenthesized_expression", DelimiterKind::Bracket, true, false},
    {"raw_string_literal", DelimiterKind::Indent, true, true},
    {"slice_pattern", DelimiterKind::Bracket, true, true},
    {"string_literal", DelimiterKind::Indent, true, true},
    {"struct_pattern", DelimiterKind::Bracket, false, true},
    {"token_tree", DelimiterKind::Bracket, true, true},
    {"token_tree_pattern", DelimiterKind::Bracket, true, true},
    {"tuple_expression", DelimiterKind::Bracket, true, true},
    {"tuple_pattern", DelimiterKind::Bracket, true, true},
    {"tuple_struct_pattern", DelimiterKind::Bracket, false, true},
    {"tuple_type", DelimiterKind::Bracket, true, true},
    {"type_parameters", DelimiterKind::Bracket, true, true},
    {"unit_expression", DelimiterKind::Bracket, true, false},
    {"unit_type", DelimiterKind::Bracket, true, false},
    {"use_list", DelimiterKind::Bracket, true, true},
    {"visibility_modifier", DelimiterKind::Bracket, false, true},
};

constexpr Entry kTypescript[] = {
    {"arguments", DelimiterKind::Bracket, true, true},
    {"array", DelimiterKind::Bracket, true, true},
    {"array_pattern", DelimiterKind::Bracket, true, true},
    {"array_type", DelimiterKind::Bracket, false, false},
    {"class_body", DelimiterKind::Bracket, true, true},
    {"computed_property_name", DelimiterKind::Bracket, true, false},
    {"decorator_parenthesized_expression", DelimiterKind::Bracket, true, true},
    {"enum_body", DelimiterKind::Bracket, true, true},
    {"export_clause", DelimiterKind::Bracket, true, true},
    {"formal_parameters", DelimiterKind::Bracket, true, true},
    {"import_require_clause", DelimiterKind::Bracket, false, false},
    {"jsx_expression", DelimiterKind::Bracket, true, true},
    {"jsx_opening_element", DelimiterKind::Bracket, true, true},
    {"lookup_type", DelimiterKind::Bracket, false, false},
    {"named_imports", DelimiterKind::Bracket, true, true},
    {"object", DelimiterKind::Bracket, true, true},
    {"object_pattern", DelimiterKind::Bracket, true, true},
    {"object_type", DelimiterKind::Bracket, true, true},
    {"parenthesized_expression", DelimiterKind::Bracket, true, true},
    {"parenthesized_type", DelimiterKind::Bracket, true, false},
    {"statement_block", DelimiterKind::Bracket, true, true},
    {"subscript_expression", DelimiterKind::Bracket, false, false},
    {"switch_body", DelimiterKind::Bracket, true, true},
    {"tuple_type", DelimiterKind::Bracket, true, true},
    {"type_arguments", DelimiterKind::Bracket, true, true},
    {"type_parameters", DelimiterKind::Bracket, true, true},
};

const std::map<std::string, std::map<std::string, DelimitedBody>>& Tables() {
    static const std::map<std::string, std::map<std::string, DelimitedBody>> kTables = [] {
        std::map<std::string, std::map<std::string, DelimitedBody>> built;
        const auto load = [&built](std::string_view language, const Entry* entries,
                                   std::size_t count) {
            auto& table = built[std::string(language)];
            for (std::size_t i = 0; i < count; ++i) {
                table.emplace(std::string(entries[i].node),
                              DelimitedBody{entries[i].kind, entries[i].openerIsFirst,
                                            entries[i].listLikeInterior});
            }
        };
        load("c", kC, std::size(kC));
        load("clojure", kClojure, std::size(kClojure));
        load("cpp", kCpp, std::size(kCpp));
        load("csharp", kCsharp, std::size(kCsharp));
        load("go", kGo, std::size(kGo));
        load("java", kJava, std::size(kJava));
        load("javascript", kJavascript, std::size(kJavascript));
        load("json", kJson, std::size(kJson));
        load("kotlin", kKotlin, std::size(kKotlin));
        load("python", kPython, std::size(kPython));
        load("rust", kRust, std::size(kRust));
        load("typescript", kTypescript, std::size(kTypescript));
        return built;
    }();
    return kTables;
}

} // namespace

const std::map<std::string, DelimitedBody>& TableFor(std::string_view language) {
    static const std::map<std::string, DelimitedBody> kEmpty;
    const auto it = Tables().find(std::string(language));
    return it == Tables().end() ? kEmpty : it->second;
}

std::vector<std::string> TabledLanguages() {
    std::vector<std::string> names;
    for (const auto& [language, table] : Tables()) names.push_back(language);
    return names;
}

} // namespace ned::editor::imprint
