//
// `ned-langc`: the grammar table generator as its own program.
//
// It exists as a separate executable for the build graph's sake. Every
// bundled language's `tables` is generated by running this
// (CMake/LanguageTables.cmake), so whatever the tables depend on is rebuilt
// on every editor source change. Pointed at `ned`, that meant one edit
// anywhere in the editor invalidated all of them; pointed here, it is only
// the generator's own ~15 translation units -- which depend on no editor
// code at all, just Editor/JanetData.h and utf8proc.
//
// `ned --compile-language` stays, running the same ned_grammar_compile
// library in-process, since the editor compiles out-of-tree language
// packages at runtime. This argv shape matches it, `--compile-language`
// included and ignored, so either program takes the same command line.
//

#include <cstring>
#include <iostream>
#include <string>
#include <vector>

#include "Editor/Grammar/Compile/CompileCommand.h"

namespace {

int Usage(std::ostream& out, int code) {
    out << "usage: ned-langc [--compile-language] <language directory or grammar.janet>...\n"
           "                 [-o|--output <file>]\n"
           "\n"
           "Compiles each language's grammar.janet to the `tables` file ned's parser\n"
           "runs. Without --output each language's tables are written beside its\n"
           "grammar; --output names one file and takes exactly one language.\n";
    return code;
}

} // namespace

int main(int argc, char** argv) {
    std::vector<std::string> sources;
    std::string              output;

    for (int i = 1; i < argc; ++i) {
        const char* arg = argv[i];
        if (std::strcmp(arg, "-h") == 0 || std::strcmp(arg, "--help") == 0)
            return Usage(std::cout, 0);
        if (std::strcmp(arg, "--compile-language") == 0)
            continue; // accepted so `ned`'s own command line works verbatim
        if (std::strcmp(arg, "-o") == 0 || std::strcmp(arg, "--output") == 0) {
            if (++i == argc) {
                std::cerr << "ned-langc: " << arg << " needs a file\n";
                return 2;
            }
            output = argv[i];
            continue;
        }
        if (arg[0] == '-' && arg[1] != '\0') {
            std::cerr << "ned-langc: unknown option " << arg << "\n";
            return Usage(std::cerr, 2);
        }
        sources.emplace_back(arg);
    }

    if (sources.empty())
        return Usage(std::cerr, 2);
    return ned::editor::grammar::compile::RunCompileLanguage(sources, output, std::cout, std::cerr);
}
