#!/usr/bin/env python3
"""Generates Source/Editor/Grammar/Compile/UnicodeTables.cpp: the codepoint
ranges of the properties a grammar's regex may name that utf8proc does not
expose -- the four identifier properties (\\p{XID_Start}, \\p{XID_Continue},
\\p{ID_Start}, \\p{ID_Continue}) and the six emoji properties
(\\p{Emoji}, \\p{Emoji_Presentation}, \\p{Emoji_Modifier},
\\p{Emoji_Modifier_Base}, \\p{Emoji_Component}, \\p{Extended_Pictographic}).

General categories and case folding come from utf8proc at runtime. XID_*
come from Python's own identifier rules (str.isidentifier is defined by
exactly XID_Start/XID_Continue); ID_* are XID_* plus the small fixed set of
characters NFKC-closure removes from them (DerivedCoreProperties.txt); the
emoji properties are read from Tools/unicode/emoji-data.txt (the UCD file,
vendored -- refresh it from unicode.org/Public/UCD/latest/ucd/emoji/).

Regenerate:  Tools/gen-unicode-tables.py
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "Source" / "Editor" / "Grammar" / "Compile" / "UnicodeTables.cpp"
EMOJI_DATA = Path(__file__).resolve().parent / "unicode" / "emoji-data.txt"
EMOJI_PROPERTIES = ["Emoji", "Emoji_Presentation", "Emoji_Modifier", "Emoji_Modifier_Base", "Emoji_Component", "Extended_Pictographic"]

# ID_Start minus XID_Start, and ID_Continue minus XID_Continue.
ID_START_EXTRA = [0x037A, 0x0E33, 0x0EB3, 0x309B, 0x309C, *range(0xFC5E, 0xFC64), 0xFDFA, 0xFDFB,
                  0xFE70, 0xFE72, 0xFE74, 0xFE76, 0xFE78, 0xFE7A, 0xFE7C, 0xFE7E, 0xFF9E, 0xFF9F]
ID_CONTINUE_EXTRA = [0x037A, 0x309B, 0x309C, *range(0xFC5E, 0xFC64), 0xFDFA, 0xFDFB,
                     0xFE70, 0xFE72, 0xFE74, 0xFE76, 0xFE78, 0xFE7A, 0xFE7C, 0xFE7E, 0xFF9E, 0xFF9F]


def ranges(predicate) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    start = None
    for cp in range(0x110000):
        if predicate(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp))
            start = None
    if start is not None:
        out.append((start, 0x110000))
    return out


def emoji_tables() -> tuple[str, dict[str, list[tuple[int, int]]]]:
    """The emoji properties as half-open range tables, merged where adjacent."""
    version = "?"
    raw: dict[str, list[tuple[int, int]]] = {name: [] for name in EMOJI_PROPERTIES}
    for line in EMOJI_DATA.read_text().splitlines():
        if line.startswith("# Version:"):
            version = line.split(":", 1)[1].strip()
        body = line.split("#", 1)[0].strip()
        if not body:
            continue
        codepoints, prop = (part.strip() for part in body.split(";", 1))
        if prop not in raw:
            continue
        first, _, last = codepoints.partition("..")
        raw[prop].append((int(first, 16), int(last or first, 16) + 1))
    tables: dict[str, list[tuple[int, int]]] = {}
    for prop, spans in raw.items():
        merged: list[tuple[int, int]] = []
        for start, end in sorted(spans):
            if merged and merged[-1][1] >= start:
                merged[-1] = (merged[-1][0], max(merged[-1][1], end))
            else:
                merged.append((start, end))
        tables[prop] = merged
    return version, tables


def main() -> None:
    emoji_version, emoji = emoji_tables()
    xid_start = ranges(lambda cp: chr(cp).isidentifier())
    xid_continue = ranges(lambda cp: ("a" + chr(cp)).isidentifier())
    extra_start = set(ID_START_EXTRA)
    extra_continue = set(ID_CONTINUE_EXTRA)
    id_start = ranges(lambda cp: chr(cp).isidentifier() or cp in extra_start)
    id_continue = ranges(lambda cp: ("a" + chr(cp)).isidentifier() or cp in extra_continue)

    lines = [
        "// GENERATED by Tools/gen-unicode-tables.py -- do not edit by hand.",
        f"// Unicode {unicodedata.unidata_version} (Python {sys.version.split()[0]}); emoji-data.txt {emoji_version}.",
        "",
        '#include "Editor/Grammar/Compile/UnicodeTables.h"',
        "",
        "namespace ned::editor::grammar::compile::unicode {",
        "",
    ]
    tables = [("kXidStart", xid_start), ("kXidContinue", xid_continue), ("kIdStart", id_start), ("kIdContinue", id_continue)]
    tables += [("k" + prop.replace("_", ""), emoji[prop]) for prop in EMOJI_PROPERTIES]
    for name, table in tables:
        lines.append(f"const std::uint32_t {name}[] = {{")
        row = []
        for start, end in table:
            row.append(f"0x{start:X}, 0x{end:X},")
            if len(row) == 6:
                lines.append("    " + " ".join(row))
                row = []
        if row:
            lines.append("    " + " ".join(row))
        lines.append("};")
        lines.append(f"const std::size_t {name}Count = {len(table)};")
        lines.append("")
    lines.append("} // namespace ned::editor::grammar::compile::unicode")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(OUT.parents[4])}: XID_Start {len(xid_start)} ranges, XID_Continue {len(xid_continue)} ranges, Emoji {len(emoji['Emoji'])} ranges")


if __name__ == "__main__":
    main()
