# Generates C++ constants from checked-in Janet source (plugins and per-
# language query/definition data) at configure time, so this codebase has no
# Resources/-style loose-runtime-file convention. Included from the root
# CMakeLists.txt before add_subdirectory(Source); on return, the current
# directory scope's NED_GENERATED_QUERY_SOURCES variable holds the generated
# .cpp files, which Source/CMakeLists.txt adds to ned_lib.

function(ned_embed_janet_plugin plugin_file symbol)
    if (NOT EXISTS "${plugin_file}")
        message(FATAL_ERROR "ned_embed_janet_plugin: ${plugin_file} not found")
    endif()
    # Configure-time-read staleness trap: file(READ) only runs when CMake
    # reconfigures, so an edited plugin file needs to be a configure
    # dependency or a rebuild silently keeps embedding the old content.
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${plugin_file}")
    file(READ "${plugin_file}" plugin_content)
    string(CONCAT generated_content
        "// Auto-generated by CMake's ned_embed_janet_plugin (see CMakeLists.txt)\n"
        "// from ${plugin_file} -- do not edit by hand, changes will be\n"
        "// overwritten on the next configure.\n"
        "namespace ned::janet::plugins {\n"
        "extern const char* const k${symbol} = R\"NED_PLUGIN_EOF(${plugin_content})NED_PLUGIN_EOF\";\n"
        "}\n")
    set(generated_file "${CMAKE_BINARY_DIR}/ned_generated/EmbeddedPlugin_${symbol}.cpp")
    file(WRITE "${generated_file}" "${generated_content}")
    set(NED_GENERATED_QUERY_SOURCES "${NED_GENERATED_QUERY_SOURCES}" "${generated_file}" PARENT_SCOPE)
endfunction()

ned_embed_janet_plugin("${CMAKE_CURRENT_SOURCE_DIR}/Source/Janet/Plugins/vcs-git.janet" VcsGit)
ned_embed_janet_plugin("${CMAKE_CURRENT_SOURCE_DIR}/Source/Janet/Plugins/gradients.janet" Gradients)
ned_embed_janet_plugin("${CMAKE_CURRENT_SOURCE_DIR}/Source/Janet/Plugins/languages.janet" Languages)

# Every file under Source/Languages/ -- a language's query data and its
# language.janet -- compiled into one path -> content table
# (Editor/LanguageFiles.h's EmbeddedLanguageFiles). One glob rather than one
# embed call per file: adding a language or a query kind is adding a file,
# not a CMake line, a Queries.h extern and a factory initializer. The glob is
# CONFIGURE_DEPENDS so a new file triggers a reconfigure, and each file is a
# configure dependency so an edited one does -- the same file(READ) staleness
# trap ned_embed_janet_plugin documents above.
function(ned_embed_language_files)
    file(GLOB_RECURSE language_files CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/Source/Languages/*.janet")
    list(SORT language_files)
    string(CONCAT generated_content
        "// Auto-generated by CMake's ned_embed_language_files (see CMakeLists.txt)\n"
        "// from Source/Languages/ -- do not edit by hand, changes will be\n"
        "// overwritten on the next configure.\n"
        "#include \"Editor/LanguageFiles.h\"\n"
        "namespace ned::editor {\n"
        "namespace {\n"
        "const EmbeddedLanguageFile kFiles[] = {\n")
    foreach(language_file IN LISTS language_files)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${language_file}")
        file(RELATIVE_PATH relative_path "${CMAKE_CURRENT_SOURCE_DIR}/Source/Languages" "${language_file}")
        file(READ "${language_file}" file_content)
        string(APPEND generated_content
            "    {\"${relative_path}\", R\"NEDLANGFILE(${file_content})NEDLANGFILE\"},\n")
    endforeach()
    # A zero-length array is not C++; an empty Source/Languages/ (never the
    # case once the bundled files exist) gets an empty span instead.
    string(APPEND generated_content
        "    {\"\", \"\"},\n"
        "};\n"
        "} // namespace\n"
        "std::span<const EmbeddedLanguageFile> EmbeddedLanguageFiles() {\n"
        "    return {kFiles, sizeof(kFiles) / sizeof(kFiles[0]) - 1};\n"
        "}\n"
        "} // namespace ned::editor\n")
    set(generated_file "${CMAKE_BINARY_DIR}/ned_generated/EmbeddedLanguageFiles.cpp")
    file(WRITE "${generated_file}" "${generated_content}")
    set(NED_GENERATED_QUERY_SOURCES "${NED_GENERATED_QUERY_SOURCES}" "${generated_file}" PARENT_SCOPE)
endfunction()

ned_embed_language_files()
